import type { Concept } from "@/lib/types";

/**
 * Ordered N5 curriculum concepts. The learning engine walks this list
 * and respects prerequisites + mastery before advancing.
 */

function concept(
  partial: Omit<Concept, "contentIds" | "estimatedMinutes"> & {
    estimatedMinutes?: number;
  }
): Concept {
  const vocabularyIds = partial.vocabularyIds ?? [];
  const grammarIds = partial.grammarIds ?? [];
  const kanjiIds = partial.kanjiIds ?? [];
  const kanaIds = partial.kanaIds ?? [];
  return {
    estimatedMinutes: 20,
    ...partial,
    vocabularyIds,
    grammarIds,
    kanjiIds,
    kanaIds,
    contentIds: [...vocabularyIds, ...grammarIds, ...kanjiIds, ...kanaIds],
  };
}

export const CONCEPTS: Concept[] = [
  // ─── Phase 1: Foundations ───────────────────────────────────────────
  concept({
    id: "c-pronunciation",
    unitId: "unit-pronunciation",
    type: "kana",
    title: "Japanese Sounds",
    description:
      "Vowels, mora timing, and how Japanese pronunciation differs from English",
    order: 1,
    difficulty: 1,
    lessonType: "NEW_CONCEPT",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-hira-vowels",
    unitId: "unit-hiragana-basic",
    type: "kana",
    title: "Hiragana · Vowels",
    description: "Learn あ い う え お — the five Japanese vowels",
    order: 2,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: ["h-a", "h-i", "h-u", "h-e", "h-o"],
  }),
  concept({
    id: "c-hira-k",
    unitId: "unit-hiragana-basic",
    type: "kana",
    title: "Hiragana · K Row",
    description: "Learn か き く け こ",
    order: 3,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: ["h-ka", "h-ki", "h-ku", "h-ke", "h-ko"],
  }),
  concept({
    id: "c-hira-s",
    unitId: "unit-hiragana-basic",
    type: "kana",
    title: "Hiragana · S Row",
    description: "Learn さ し す せ そ",
    order: 4,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: ["h-sa", "h-shi", "h-su", "h-se", "h-so"],
  }),
  concept({
    id: "c-hira-t",
    unitId: "unit-hiragana-basic",
    type: "kana",
    title: "Hiragana · T Row",
    description: "Learn た ち つ て と",
    order: 5,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: ["h-ta", "h-chi", "h-tsu", "h-te", "h-to"],
  }),
  concept({
    id: "c-hira-n",
    unitId: "unit-hiragana-basic",
    type: "kana",
    title: "Hiragana · N Row",
    description: "Learn な に ぬ ね の",
    order: 6,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: ["h-na", "h-ni", "h-nu", "h-ne", "h-no"],
  }),
  concept({
    id: "c-hira-h",
    unitId: "unit-hiragana-basic",
    type: "kana",
    title: "Hiragana · H Row",
    description: "Learn は ひ ふ へ ほ",
    order: 7,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: ["h-ha", "h-hi", "h-fu", "h-he", "h-ho"],
  }),
  concept({
    id: "c-hira-m",
    unitId: "unit-hiragana-basic",
    type: "kana",
    title: "Hiragana · M Row",
    description: "Learn ま み む め も",
    order: 8,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: ["h-ma", "h-mi", "h-mu", "h-me", "h-mo"],
  }),
  concept({
    id: "c-hira-y",
    unitId: "unit-hiragana-basic",
    type: "kana",
    title: "Hiragana · Y Row",
    description: "Learn や ゆ よ",
    order: 9,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: ["h-ya", "h-yu", "h-yo"],
  }),
  concept({
    id: "c-hira-r",
    unitId: "unit-hiragana-basic",
    type: "kana",
    title: "Hiragana · R Row",
    description: "Learn ら り る れ ろ",
    order: 10,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: ["h-ra", "h-ri", "h-ru", "h-re", "h-ro"],
  }),
  concept({
    id: "c-hira-w",
    unitId: "unit-hiragana-basic",
    type: "kana",
    title: "Hiragana · W Row",
    description: "Learn わ and を",
    order: 11,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: ["h-wa", "h-wo"],
  }),
  concept({
    id: "c-hira-nn",
    unitId: "unit-hiragana-basic",
    type: "kana",
    title: "Hiragana · ん",
    description: "Learn the syllabic nasal ん",
    order: 12,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: ["h-n"],
  }),
  concept({
    id: "c-hira-dakuten",
    unitId: "unit-hiragana-voiced",
    type: "kana",
    title: "Hiragana · Voiced Sounds",
    description:
      "Dakuten and handakuten: が行・ざ行・だ行・ば行・ぱ行",
    order: 13,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [
      "h-ga",
      "h-gi",
      "h-gu",
      "h-ge",
      "h-go",
      "h-za",
      "h-ji",
      "h-zu",
      "h-ze",
      "h-zo",
      "h-da",
      "h-dji",
      "h-dzu",
      "h-de",
      "h-do",
      "h-ba",
      "h-bi",
      "h-bu",
      "h-be",
      "h-bo",
      "h-pa",
      "h-pi",
      "h-pu",
      "h-pe",
      "h-po",
    ],
  }),
  concept({
    id: "c-hira-yoon",
    unitId: "unit-hiragana-voiced",
    type: "kana",
    title: "Hiragana · Combined Sounds",
    description: "Yōon combinations (きゃ・しゃ・ちゃ…) and the small っ",
    order: 14,
    difficulty: 2,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [
      "h-kya",
      "h-kyu",
      "h-kyo",
      "h-sha",
      "h-shu",
      "h-sho",
      "h-cha",
      "h-chu",
      "h-cho",
      "h-nya",
      "h-nyu",
      "h-nyo",
      "h-hya",
      "h-hyu",
      "h-hyo",
      "h-mya",
      "h-myu",
      "h-myo",
      "h-rya",
      "h-ryu",
      "h-ryo",
      "h-gya",
      "h-gyu",
      "h-gyo",
      "h-ja",
      "h-ju",
      "h-jo",
      "h-bya",
      "h-byu",
      "h-byo",
      "h-pya",
      "h-pyu",
      "h-pyo",
      "h-small-tsu",
    ],
  }),
  concept({
    id: "c-hira-review",
    unitId: "unit-hiragana-practice",
    type: "kana",
    title: "Hiragana Review",
    description: "Review and solidify all hiragana characters",
    order: 15,
    difficulty: 2,
    lessonType: "REVIEW",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [
      "h-a",
      "h-i",
      "h-u",
      "h-e",
      "h-o",
      "h-ka",
      "h-ki",
      "h-ku",
      "h-sa",
      "h-shi",
      "h-ta",
      "h-chi",
      "h-tsu",
      "h-na",
      "h-ha",
      "h-ma",
      "h-ya",
      "h-ra",
      "h-wa",
      "h-n",
      "h-ga",
      "h-za",
      "h-da",
      "h-ba",
      "h-pa",
      "h-sha",
      "h-cha",
      "h-ja",
      "h-small-tsu",
    ],
  }),

  // ─── Phase 2: Katakana ──────────────────────────────────────────────
  concept({
    id: "c-kata-vowels",
    unitId: "unit-katakana-basic",
    type: "kana",
    title: "Katakana · Vowels",
    description: "Learn ア イ ウ エ オ",
    order: 16,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: ["k-a", "k-i", "k-u", "k-e", "k-o"],
  }),
  concept({
    id: "c-kata-k-s",
    unitId: "unit-katakana-basic",
    type: "kana",
    title: "Katakana · K and S Rows",
    description: "Learn カ行 and サ行",
    order: 17,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [
      "k-ka",
      "k-ki",
      "k-ku",
      "k-ke",
      "k-ko",
      "k-sa",
      "k-shi",
      "k-su",
      "k-se",
      "k-so",
    ],
  }),
  concept({
    id: "c-kata-t-n",
    unitId: "unit-katakana-basic",
    type: "kana",
    title: "Katakana · T and N Rows",
    description: "Learn タ行 and ナ行",
    order: 18,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [
      "k-ta",
      "k-chi",
      "k-tsu",
      "k-te",
      "k-to",
      "k-na",
      "k-ni",
      "k-nu",
      "k-ne",
      "k-no",
    ],
  }),
  concept({
    id: "c-kata-h-m",
    unitId: "unit-katakana-basic",
    type: "kana",
    title: "Katakana · H and M Rows",
    description: "Learn ハ行 and マ行",
    order: 19,
    difficulty: 1,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [
      "k-ha",
      "k-hi",
      "k-fu",
      "k-he",
      "k-ho",
      "k-ma",
      "k-mi",
      "k-mu",
      "k-me",
      "k-mo",
    ],
  }),
  concept({
    id: "c-kata-yrwn",
    unitId: "unit-katakana-basic",
    type: "kana",
    title: "Katakana · Y, R, W, and N",
    description: "Learn ヤ行・ラ行・ワヲ・ン",
    order: 20,
    difficulty: 2,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [
      "k-ya",
      "k-yu",
      "k-yo",
      "k-ra",
      "k-ri",
      "k-ru",
      "k-re",
      "k-ro",
      "k-wa",
      "k-wo",
      "k-n",
    ],
  }),
  concept({
    id: "c-kata-dakuten",
    unitId: "unit-katakana-advanced",
    type: "kana",
    title: "Katakana · Voiced Sounds",
    description: "Katakana dakuten and handakuten rows",
    order: 21,
    difficulty: 2,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [
      "k-ga",
      "k-gi",
      "k-gu",
      "k-ge",
      "k-go",
      "k-za",
      "k-ji",
      "k-zu",
      "k-ze",
      "k-zo",
      "k-da",
      "k-dji",
      "k-dzu",
      "k-de",
      "k-do",
      "k-ba",
      "k-bi",
      "k-bu",
      "k-be",
      "k-bo",
      "k-pa",
      "k-pi",
      "k-pu",
      "k-pe",
      "k-po",
    ],
  }),
  concept({
    id: "c-kata-yoon",
    unitId: "unit-katakana-advanced",
    type: "kana",
    title: "Katakana · Combined Sounds",
    description: "Katakana yōon, small ッ, and the long-vowel mark ー",
    order: 22,
    difficulty: 2,
    lessonType: "KANA",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [
      "k-kya",
      "k-kyu",
      "k-kyo",
      "k-sha",
      "k-shu",
      "k-sho",
      "k-cha",
      "k-chu",
      "k-cho",
      "k-nya",
      "k-nyu",
      "k-nyo",
      "k-hya",
      "k-hyu",
      "k-hyo",
      "k-mya",
      "k-myu",
      "k-myo",
      "k-rya",
      "k-ryu",
      "k-ryo",
      "k-gya",
      "k-gyu",
      "k-gyo",
      "k-ja",
      "k-ju",
      "k-jo",
      "k-bya",
      "k-byu",
      "k-byo",
      "k-pya",
      "k-pyu",
      "k-pyo",
      "k-small-tsu",
      "k-chouon",
    ],
  }),
  concept({
    id: "c-kata-loanwords",
    unitId: "unit-katakana-advanced",
    type: "vocabulary",
    title: "Katakana Loanwords",
    description: "Everyday loanwords written in katakana",
    order: 23,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-koohii",
      "v-pan",
      "v-basu",
      "v-takushii",
      "v-hoteru",
      "v-pasokon",
      "v-pen",
      "v-biiru",
      "v-juusu",
      "v-raamen",
      "v-supootsu",
      "v-pinku",
      "v-keeki",
      "v-banana",
      "v-geemu",
      "v-kaado",
      "v-super",
      "v-konbini",
      "v-depato",
      "v-resutoran",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),

  // ─── Phase 3: Basic Japanese ────────────────────────────────────────
  concept({
    id: "c-word-order",
    unitId: "unit-sentence-basics",
    type: "grammar",
    title: "Japanese Word Order",
    description: "Subject–object–verb order and how Japanese sentences are built",
    order: 24,
    difficulty: 2,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-watashi", "v-gakusei", "v-hon", "v-nihongo"],
    grammarIds: ["g-word-order"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-greetings",
    unitId: "unit-sentence-basics",
    type: "vocabulary",
    title: "Greetings and Basics",
    description: "Essential greetings and polite everyday phrases",
    order: 25,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-konnichiwa",
      "v-ohayou",
      "v-konbanwa",
      "v-arigatou",
      "v-sumimasen",
      "v-sayounara",
      "v-hai",
      "v-iie",
      "v-onegaishimasu",
      "v-douzo",
      "v-hajimemashite",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-pronouns",
    unitId: "unit-sentence-basics",
    type: "grammar",
    title: "Personal Pronouns",
    description: "I, you, he, she, and how pronouns work in Japanese",
    order: 26,
    difficulty: 2,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-watashi", "v-anata", "v-kare", "v-kanojo"],
    grammarIds: ["g-pronouns"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-desu",
    unitId: "unit-sentence-basics",
    type: "grammar",
    title: "Describing with です",
    description: "Make polite identity and description sentences with です",
    order: 27,
    difficulty: 2,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-watashi", "v-gakusei", "v-sensei", "v-nihon"],
    grammarIds: ["g-desu"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-dewa-arimasen",
    unitId: "unit-sentence-basics",
    type: "grammar",
    title: "Negative です",
    description: "Say what something is not with ではありません / じゃありません",
    order: 28,
    difficulty: 2,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-watashi", "v-gakusei", "v-sensei", "v-nihonjin"],
    grammarIds: ["g-dewa-arimasen"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-questions",
    unitId: "unit-questions-demo",
    type: "grammar",
    title: "Asking Questions with か",
    description: "Turn statements into yes/no questions with か",
    order: 29,
    difficulty: 2,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-gakusei", "v-sensei", "v-hai", "v-iie"],
    grammarIds: ["g-ka-questions"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-demonstratives-1",
    unitId: "unit-questions-demo",
    type: "grammar",
    title: "This, That, and That Over There",
    description: "Learn これ・それ・あれ for pointing at things",
    order: 30,
    difficulty: 2,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-kore", "v-sore", "v-are", "v-hon"],
    grammarIds: ["g-kore-sore-are"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-demonstratives-2",
    unitId: "unit-questions-demo",
    type: "grammar",
    title: "This/That + Noun",
    description: "Use この・その・あの before nouns",
    order: 31,
    difficulty: 2,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-hon", "v-pen", "v-kaban", "v-denwa"],
    grammarIds: ["g-kono-sono-ano"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-numbers",
    unitId: "unit-numbers-time",
    type: "vocabulary",
    title: "Numbers and Counters",
    description: "Count from 1–10, 100, and the first Japanese counters",
    order: 32,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-ichi",
      "v-ni",
      "v-san",
      "v-yon",
      "v-go",
      "v-roku",
      "v-nana",
      "v-hachi",
      "v-kyuu",
      "v-juu",
      "v-hyaku",
      "v-zero",
      "v-hitotsu",
      "v-futatsu",
      "v-mittsu",
      "v-yottsu",
      "v-itsutsu",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-time",
    unitId: "unit-numbers-time",
    type: "vocabulary",
    title: "Telling Time",
    description: "Hours, minutes, morning/afternoon, and time-of-day words",
    order: 33,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-kyou",
      "v-ashita",
      "v-kinou",
      "v-ima",
      "v-asa",
      "v-hiru",
      "v-ban",
      "v-yoru",
      "v-ji",
      "v-fun",
      "v-gozen",
      "v-gogo",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-days",
    unitId: "unit-numbers-time",
    type: "vocabulary",
    title: "Days of the Week",
    description: "Weekdays, weekends, and 毎日",
    order: 34,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-getsuyoubi",
      "v-kayoubi",
      "v-suiyoubi",
      "v-mokuyoubi",
      "v-kinyoubi",
      "v-doyoubi",
      "v-nichiyoubi",
      "v-mainichi",
      "v-shuumatsu",
      "v-youbi",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),

  // ─── Phase 4: Particles ─────────────────────────────────────────────
  concept({
    id: "c-particle-wa",
    unitId: "unit-particles-topic",
    type: "particle",
    title: "Topic Particle は",
    description: "Mark the topic of a sentence with は",
    order: 35,
    difficulty: 2,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-watashi", "v-gakusei", "v-hon"],
    grammarIds: ["g-wa"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-particle-mo",
    unitId: "unit-particles-topic",
    type: "particle",
    title: "Also/Too with も",
    description: "Add items to a topic with も",
    order: 36,
    difficulty: 2,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-watashi", "v-tomodachi", "v-gakusei"],
    grammarIds: ["g-mo"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-particle-no",
    unitId: "unit-particles-topic",
    type: "particle",
    title: "Possession with の",
    description: "Connect nouns for possession and description with の",
    order: 37,
    difficulty: 2,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-watashi", "v-tomodachi", "v-hon", "v-namae"],
    grammarIds: ["g-no"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-particle-wo",
    unitId: "unit-particles-object",
    type: "particle",
    title: "Object Particle を",
    description: "Mark the direct object of a verb with を",
    order: 38,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-hon", "v-koohii", "v-eiga"],
    grammarIds: ["g-wo"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-particle-ni",
    unitId: "unit-particles-object",
    type: "particle",
    title: "Destination and Time with に",
    description: "Mark destinations, times, and targets with に",
    order: 39,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-gakkou", "v-uchi", "v-eki"],
    grammarIds: ["g-ni"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-particle-e",
    unitId: "unit-particles-object",
    type: "particle",
    title: "Direction with へ",
    description: "Mark direction of movement with へ",
    order: 40,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-gakkou", "v-nihon", "v-uchi"],
    grammarIds: ["g-e"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-particle-de",
    unitId: "unit-particles-place",
    type: "particle",
    title: "Place of Action with で",
    description: "Say where an action happens with で",
    order: 41,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-gakkou", "v-uchi", "v-resutoran", "v-toshokan"],
    grammarIds: ["g-de"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-particle-to",
    unitId: "unit-particles-place",
    type: "particle",
    title: "And / With と",
    description: "List nouns and mark companions with と",
    order: 42,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-tomodachi", "v-pan", "v-koohii"],
    grammarIds: ["g-to"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-particle-kara",
    unitId: "unit-particles-place",
    type: "particle",
    title: "From with から",
    description: "Mark starting points in time and space with から",
    order: 43,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-uchi", "v-gakkou", "v-asa"],
    grammarIds: ["g-kara"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-particle-made",
    unitId: "unit-particles-place",
    type: "particle",
    title: "Until with まで",
    description: "Mark endpoints with まで (often paired with から)",
    order: 44,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-eki", "v-gakkou", "v-ban"],
    grammarIds: ["g-made"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-particle-ga",
    unitId: "unit-particles-place",
    type: "particle",
    title: "Subject Particle が",
    description: "Contrast は and が — mark the grammatical subject",
    order: 45,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-watashi", "v-neko", "v-inu", "v-nani"],
    grammarIds: ["g-ga"],
    kanjiIds: [],
    kanaIds: [],
  }),

  // ─── Phase 5: Vocabulary Themes ─────────────────────────────────────
  concept({
    id: "c-vocab-family",
    unitId: "unit-vocab-people",
    type: "vocabulary",
    title: "Family",
    description: "Family members and household relationships",
    order: 46,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-chichi",
      "v-haha",
      "v-ani",
      "v-ane",
      "v-otouto",
      "v-imouto",
      "v-kazoku",
      "v-ryoushin",
      "v-kodomo",
      "v-otousan",
      "v-okaasan",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-people",
    unitId: "unit-vocab-people",
    type: "vocabulary",
    title: "People",
    description: "People, roles, and nationalities",
    order: 47,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-hito",
      "v-tomodachi",
      "v-gakusei",
      "v-sensei",
      "v-nihonjin",
      "v-gaikokujin",
      "v-otoko",
      "v-onna",
      "v-otona",
      "v-kaishain",
      "v-isha",
      "v-namae",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-places",
    unitId: "unit-vocab-world",
    type: "vocabulary",
    title: "Places",
    description: "Common places around town and in daily life",
    order: 48,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-gakkou",
      "v-uchi",
      "v-mise",
      "v-eki",
      "v-byouin",
      "v-ginkou",
      "v-toshokan",
      "v-kouen",
      "v-kaisha",
      "v-resutoran",
      "v-hoteru",
      "v-kuukou",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-food",
    unitId: "unit-vocab-world",
    type: "vocabulary",
    title: "Food",
    description: "Everyday foods and meals",
    order: 49,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-gohan",
      "v-pan",
      "v-niku",
      "v-sakana",
      "v-yasai",
      "v-kudamono",
      "v-tamago",
      "v-sushi",
      "v-raamen",
      "v-asagohan",
      "v-hirugohan",
      "v-bangohan",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-drinks",
    unitId: "unit-vocab-world",
    type: "vocabulary",
    title: "Drinks",
    description: "Common beverages",
    order: 50,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-mizu",
      "v-ocha",
      "v-koohii",
      "v-gyuunyuu",
      "v-biiru",
      "v-juusu",
      "v-nomimono",
      "v-koucha",
      "v-osake",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-transport",
    unitId: "unit-vocab-world",
    type: "vocabulary",
    title: "Transportation",
    description: "How people get around",
    order: 51,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-densha",
      "v-basu",
      "v-takushii",
      "v-jitensha",
      "v-kuruma",
      "v-chikatetsu",
      "v-hikouki",
      "v-fune",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-objects",
    unitId: "unit-vocab-world",
    type: "vocabulary",
    title: "Everyday Objects",
    description: "Things you use at home, school, and work",
    order: 52,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-tsukue",
      "v-isu",
      "v-mado",
      "v-doa",
      "v-kaban",
      "v-kasa",
      "v-tokei",
      "v-denwa",
      "v-pasokon",
      "v-kagi",
      "v-pen",
      "v-saifu",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-school",
    unitId: "unit-vocab-life",
    type: "vocabulary",
    title: "School Life",
    description: "Classes, homework, and study vocabulary",
    order: 53,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-nihongo",
      "v-eigo",
      "v-benkyou",
      "v-shukudai",
      "v-tesuto",
      "v-hon",
      "v-jisho",
      "v-jugyou",
      "v-kyoushitsu",
      "v-mondai",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-work",
    unitId: "unit-vocab-life",
    type: "vocabulary",
    title: "Work and Daily Routine",
    description: "Jobs, rest, and everyday activity words",
    order: 54,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-shigoto",
      "v-yasumi",
      "v-kaigi",
      "v-kaisha",
      "v-hataraku",
      "v-kaishain",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-hobbies",
    unitId: "unit-vocab-life",
    type: "vocabulary",
    title: "Hobbies",
    description: "Leisure activities and interests",
    order: 55,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-eiga",
      "v-ongaku",
      "v-supootsu",
      "v-ryokou",
      "v-shashin",
      "v-shumi",
      "v-geemu",
      "v-asobu",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-weather",
    unitId: "unit-vocab-life",
    type: "vocabulary",
    title: "Weather",
    description: "Weather conditions and hot/cold",
    order: 56,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-tenki",
      "v-ame",
      "v-yuki",
      "v-hare",
      "v-kumori",
      "v-kaze",
      "v-atsui",
      "v-samui",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-shopping",
    unitId: "unit-vocab-life",
    type: "vocabulary",
    title: "Shopping",
    description: "Money, prices, and expensive/cheap",
    order: 57,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-en",
      "v-okane",
      "v-kaado",
      "v-nedan",
      "v-kaimono",
      "v-takai",
      "v-yasui",
      "v-depato",
      "v-konbini",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-colors",
    unitId: "unit-vocab-life",
    type: "vocabulary",
    title: "Colors",
    description: "Basic color words",
    order: 58,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-aka",
      "v-ao",
      "v-kiiro",
      "v-midori",
      "v-kuro",
      "v-shiro",
      "v-chairo",
      "v-pinku",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-vocab-body",
    unitId: "unit-vocab-life",
    type: "vocabulary",
    title: "Body Parts",
    description: "Common body vocabulary",
    order: 59,
    difficulty: 2,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-atama",
      "v-me",
      "v-mimi",
      "v-kuchi",
      "v-te",
      "v-ashi",
      "v-karada",
      "v-kokoro",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),

  // ─── Phase 6: Verbs ─────────────────────────────────────────────────
  concept({
    id: "c-verbs-motion",
    unitId: "unit-verbs-core",
    type: "vocabulary",
    title: "Motion Verbs",
    description: "Go, come, return, walk, ride, and related motion verbs",
    order: 60,
    difficulty: 3,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-iku",
      "v-kuru",
      "v-kaeru",
      "v-aruku",
      "v-hashiru",
      "v-noru",
      "v-oriru",
      "v-deru",
      "v-hairu",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-verbs-daily",
    unitId: "unit-verbs-core",
    type: "vocabulary",
    title: "Daily Activity Verbs",
    description: "Eat, drink, see, listen, read, write, sleep, wake up",
    order: 61,
    difficulty: 3,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-taberu",
      "v-nomu",
      "v-miru",
      "v-kiku",
      "v-yomu",
      "v-kaku",
      "v-neru",
      "v-okiru",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-verbs-more",
    unitId: "unit-verbs-core",
    type: "vocabulary",
    title: "More Essential Verbs",
    description: "Speak, buy, meet, do, exist, wait, use, understand, teach, learn",
    order: 62,
    difficulty: 3,
    lessonType: "VOCABULARY",
    vocabularyIds: [
      "v-hanasu",
      "v-kau",
      "v-au",
      "v-suru",
      "v-aru",
      "v-iru",
      "v-matsu",
      "v-motsu",
      "v-tsukau",
      "v-wakaru",
      "v-oshieru",
      "v-narau",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-masu",
    unitId: "unit-verbs-polite",
    type: "grammar",
    title: "Polite Present with ます",
    description: "Conjugate verbs into polite present affirmative and negative",
    order: 63,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-iku", "v-taberu", "v-nomu", "v-miru", "v-suru"],
    grammarIds: ["g-masu", "g-masen"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-past-tense",
    unitId: "unit-verbs-polite",
    type: "grammar",
    title: "Talking About Yesterday",
    description: "Polite past affirmative and negative: ました / ませんでした",
    order: 64,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-iku", "v-taberu", "v-miru", "v-kinou", "v-kyou"],
    grammarIds: ["g-mashita", "g-masen-deshita"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-dictionary-form",
    unitId: "unit-verbs-polite",
    type: "grammar",
    title: "Dictionary Form",
    description: "Recognize and use the plain dictionary form of verbs",
    order: 65,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-iku", "v-taberu", "v-nomu", "v-suru", "v-kuru"],
    grammarIds: ["g-dictionary-form"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-te-form",
    unitId: "unit-verbs-te",
    type: "grammar",
    title: "The て-Form",
    description: "Form the versatile て-form used in many grammar patterns",
    order: 66,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-taberu", "v-nomu", "v-iku", "v-suru", "v-kuru"],
    grammarIds: ["g-te-form"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-te-kudasai",
    unitId: "unit-verbs-te",
    type: "grammar",
    title: "Please Do… with てください",
    description: "Make polite requests with てください",
    order: 67,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-miru", "v-kiku", "v-matsu", "v-taberu"],
    grammarIds: ["g-te-kudasai"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-te-iru",
    unitId: "unit-verbs-te",
    type: "grammar",
    title: "Ongoing Actions with ている",
    description: "Describe progressive and resultative states with ている",
    order: 68,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-taberu", "v-yomu", "v-hataraku", "v-sumu"],
    grammarIds: ["g-te-iru"],
    kanjiIds: [],
    kanaIds: [],
  }),

  // ─── Phase 7: Adjectives ────────────────────────────────────────────
  concept({
    id: "c-i-adjectives",
    unitId: "unit-adjectives",
    type: "grammar",
    title: "い-Adjectives",
    description: "Describe things with い-adjectives",
    order: 69,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: [
      "v-ookii",
      "v-chiisai",
      "v-atarashii",
      "v-furui",
      "v-takai",
      "v-yasui",
      "v-atsui",
      "v-samui",
      "v-oishii",
      "v-ii",
    ],
    grammarIds: ["g-i-adjectives"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-i-adj-forms",
    unitId: "unit-adjectives",
    type: "grammar",
    title: "い-Adjective Forms",
    description: "Negative and past forms of い-adjectives",
    order: 70,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-ookii", "v-oishii", "v-atsui", "v-tanoshii"],
    grammarIds: ["g-i-adj-negative", "g-i-adj-past"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-na-adjectives",
    unitId: "unit-adjectives",
    type: "grammar",
    title: "な-Adjectives",
    description: "Describe things with な-adjectives",
    order: 71,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: [
      "v-shizuka",
      "v-kirei",
      "v-yuumei",
      "v-benri",
      "v-suteki",
      "v-suki",
      "v-kirai",
      "v-jouzu",
      "v-heta",
      "v-genki",
    ],
    grammarIds: ["g-na-adjectives"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-na-adj-forms",
    unitId: "unit-adjectives",
    type: "grammar",
    title: "な-Adjective Forms",
    description: "Negative and past forms of な-adjectives",
    order: 72,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-shizuka", "v-kirei", "v-genki", "v-benri"],
    grammarIds: ["g-na-adj-negative", "g-na-adj-past"],
    kanjiIds: [],
    kanaIds: [],
  }),

  // ─── Phase 8: Grammar ───────────────────────────────────────────────
  concept({
    id: "c-suki",
    unitId: "unit-grammar-existence",
    type: "grammar",
    title: "Likes and Dislikes",
    description: "Express preferences with 好き / 嫌い",
    order: 73,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-suki", "v-kirai", "v-eiga", "v-koohii", "v-neko"],
    grammarIds: ["g-suki"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-existence",
    unitId: "unit-grammar-existence",
    type: "grammar",
    title: "Existence with あります / います",
    description: "Say that things and people exist or are present",
    order: 74,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-hon", "v-neko", "v-tomodachi", "v-aru", "v-iru"],
    grammarIds: ["g-arimasu-imasu"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-location",
    unitId: "unit-grammar-existence",
    type: "grammar",
    title: "Where Things Are",
    description: "Locate people and objects with にあります / にいます",
    order: 75,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: [
      "v-ue",
      "v-shita",
      "v-naka",
      "v-soto",
      "v-mae",
      "v-ushiro",
      "v-tonari",
      "v-migi",
      "v-hidari",
    ],
    grammarIds: ["g-location-ni-arimasu"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-time-expressions",
    unitId: "unit-grammar-existence",
    type: "grammar",
    title: "Time Expressions",
    description: "Talk about when events happen",
    order: 76,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-kyou", "v-ashita", "v-kinou", "v-ima", "v-ji"],
    grammarIds: ["g-time-expressions"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-frequency",
    unitId: "unit-grammar-existence",
    type: "grammar",
    title: "How Often",
    description: "Frequency adverbs: always, often, sometimes",
    order: 77,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: [
      "v-itsumo",
      "v-yoku",
      "v-tokidoki",
      "v-totemo",
      "v-sukoshi",
      "v-takusan",
    ],
    grammarIds: ["g-frequency"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-tai",
    unitId: "unit-grammar-requests",
    type: "grammar",
    title: "Wanting to Do with たい",
    description: "Express desire to do something with 〜たい",
    order: 78,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-taberu", "v-iku", "v-miru", "v-nomu"],
    grammarIds: ["g-tai"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-mashou",
    unitId: "unit-grammar-requests",
    type: "grammar",
    title: "Let's… with ましょう",
    description: "Make suggestions with 〜ましょう",
    order: 79,
    difficulty: 3,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-iku", "v-taberu", "v-miru", "v-asobu"],
    grammarIds: ["g-mashou"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-permission",
    unitId: "unit-grammar-requests",
    type: "grammar",
    title: "Asking Permission",
    description: "Ask and give permission with てもいい",
    order: 80,
    difficulty: 4,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-taberu", "v-miru", "v-hairu", "v-tsukau"],
    grammarIds: ["g-te-mo-ii"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-prohibition",
    unitId: "unit-grammar-requests",
    type: "grammar",
    title: "Please Don't…",
    description: "Ask someone not to do something with ないでください",
    order: 81,
    difficulty: 4,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-taberu", "v-nomu", "v-hairu", "v-wasureru"],
    grammarIds: ["g-naide-kudasai"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-ability",
    unitId: "unit-grammar-requests",
    type: "grammar",
    title: "Ability with ことができる",
    description: "Say what you can or cannot do",
    order: 82,
    difficulty: 4,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-hanasu", "v-oyogu", "v-hashiru", "v-nihongo"],
    grammarIds: ["g-koto-ga-dekiru"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-counters",
    unitId: "unit-grammar-connect",
    type: "grammar",
    title: "Counters",
    description: "Count people, things, and more with Japanese counters",
    order: 83,
    difficulty: 4,
    lessonType: "GRAMMAR",
    vocabularyIds: [
      "v-hitotsu",
      "v-futatsu",
      "v-mittsu",
      "v-yottsu",
      "v-itsutsu",
      "v-hito",
      "v-hon",
    ],
    grammarIds: ["g-counters"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-comparisons",
    unitId: "unit-grammar-connect",
    type: "grammar",
    title: "Comparisons",
    description: "Compare with より and ほうが",
    order: 84,
    difficulty: 4,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-ookii", "v-chiisai", "v-takai", "v-yasui", "v-oishii"],
    grammarIds: ["g-yori-hou-ga"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-reasons",
    unitId: "unit-grammar-connect",
    type: "grammar",
    title: "Giving Reasons",
    description: "Explain why with から and ので",
    order: 85,
    difficulty: 4,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-atsui", "v-isogashii", "v-byouin", "v-gakkou"],
    grammarIds: ["g-kara-reason", "g-node"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-contrast",
    unitId: "unit-grammar-connect",
    type: "grammar",
    title: "But… with けど",
    description: "Connect contrasting ideas with けど",
    order: 86,
    difficulty: 4,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-suki", "v-muzukashii", "v-omoshiroi", "v-takai"],
    grammarIds: ["g-kedo"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-conditional",
    unitId: "unit-grammar-connect",
    type: "grammar",
    title: "When / If with と",
    description: "Natural results and conditionals with と",
    order: 87,
    difficulty: 4,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-haru", "v-hana", "v-atsui", "v-mizu"],
    grammarIds: ["g-to-conditional"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-naru",
    unitId: "unit-grammar-connect",
    type: "grammar",
    title: "Becoming with なる",
    description: "Describe change of state with なる",
    order: 88,
    difficulty: 4,
    lessonType: "GRAMMAR",
    vocabularyIds: ["v-genki", "v-ookii", "v-sensei", "v-haru"],
    grammarIds: ["g-naru"],
    kanjiIds: [],
    kanaIds: [],
  }),

  // ─── Phase 9: Kanji ─────────────────────────────────────────────────
  concept({
    id: "c-kanji-numbers",
    unitId: "unit-kanji-foundation",
    type: "kanji",
    title: "Number Kanji",
    description: "Core number kanji from 一 to 十 and beyond",
    order: 89,
    difficulty: 3,
    lessonType: "KANJI",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [
      "kj-ichi",
      "kj-ni",
      "kj-san",
      "kj-shi",
      "kj-go",
      "kj-roku",
      "kj-nana",
      "kj-hachi",
      "kj-kyuu",
      "kj-juu",
    ],
    kanaIds: [],
  }),
  concept({
    id: "c-kanji-time",
    unitId: "unit-kanji-foundation",
    type: "kanji",
    title: "Time Kanji",
    description: "Days, months, hours, and time-related characters",
    order: 90,
    difficulty: 3,
    lessonType: "KANJI",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [
      "kj-nichi",
      "kj-getsu",
      "kj-nen",
      "kj-ji",
      "kj-fun",
      "kj-ima",
      "kj-mae",
      "kj-ato",
      "kj-shuu",
      "kj-mai",
    ],
    kanaIds: [],
  }),
  concept({
    id: "c-kanji-people",
    unitId: "unit-kanji-foundation",
    type: "kanji",
    title: "People Kanji",
    description: "People and family characters",
    order: 91,
    difficulty: 3,
    lessonType: "KANJI",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [
      "kj-hito",
      "kj-otoko",
      "kj-onna",
      "kj-ko",
      "kj-chichi",
      "kj-haha",
      "kj-tomo",
      "kj-ani",
      "kj-ane",
      "kj-otouto",
      "kj-imouto",
    ],
    kanaIds: [],
  }),
  concept({
    id: "c-kanji-nature",
    unitId: "unit-kanji-world",
    type: "kanji",
    title: "Nature Kanji",
    description: "Mountains, rivers, trees, rain, and sky",
    order: 92,
    difficulty: 3,
    lessonType: "KANJI",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [
      "kj-yama",
      "kj-kawa",
      "kj-ten",
      "kj-ame",
      "kj-hana",
      "kj-ki-tree",
      "kj-hayashi",
      "kj-mori",
      "kj-umi",
      "kj-sora",
    ],
    kanaIds: [],
  }),
  concept({
    id: "c-kanji-places",
    unitId: "unit-kanji-world",
    type: "kanji",
    title: "Place Kanji",
    description: "Schools, stations, countries, and directions",
    order: 93,
    difficulty: 3,
    lessonType: "KANJI",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [
      "kj-kou",
      "kj-sha",
      "kj-mise",
      "kj-eki",
      "kj-kuni",
      "kj-higashi",
      "kj-nishi",
      "kj-minami",
      "kj-kita",
      "kj-machi",
      "kj-ie",
    ],
    kanaIds: [],
  }),
  concept({
    id: "c-kanji-daily",
    unitId: "unit-kanji-world",
    type: "kanji",
    title: "Daily Life Kanji",
    description: "Books, language, school, and everyday characters",
    order: 94,
    difficulty: 4,
    lessonType: "KANJI",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [
      "kj-hon",
      "kj-go-lang",
      "kj-bun",
      "kj-gaku",
      "kj-sei",
      "kj-nani",
      "kj-watashi",
      "kj-den",
      "kj-kuruma",
      "kj-ue",
      "kj-shita",
      "kj-naka",
    ],
    kanaIds: [],
  }),
  concept({
    id: "c-kanji-verbs",
    unitId: "unit-kanji-actions",
    type: "kanji",
    title: "Verb Kanji",
    description: "Common action kanji: go, eat, see, write, and more",
    order: 95,
    difficulty: 4,
    lessonType: "KANJI",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [
      "kj-iku",
      "kj-kuru",
      "kj-taberu",
      "kj-nomu",
      "kj-miru",
      "kj-kiku",
      "kj-yomu",
      "kj-kaku",
      "kj-hanasu",
      "kj-kau",
      "kj-deru",
      "kj-kaeru",
    ],
    kanaIds: [],
  }),
  concept({
    id: "c-kanji-adjectives",
    unitId: "unit-kanji-actions",
    type: "kanji",
    title: "Adjective and Body Kanji",
    description: "Size, price, and body-part characters",
    order: 96,
    difficulty: 4,
    lessonType: "KANJI",
    vocabularyIds: [],
    grammarIds: [],
    kanjiIds: [
      "kj-yasui",
      "kj-taka",
      "kj-chiisai",
      "kj-ookii",
      "kj-mimi",
      "kj-me",
      "kj-kuchi",
      "kj-te",
      "kj-ashi",
    ],
    kanaIds: [],
  }),

  // ─── Phase 10: Integration ──────────────────────────────────────────
  concept({
    id: "c-reading-1",
    unitId: "unit-integration",
    type: "reading",
    title: "Reading Practice 1",
    description: "Read short N5 passages using familiar vocabulary",
    order: 97,
    difficulty: 4,
    lessonType: "READING",
    vocabularyIds: [
      "v-watashi",
      "v-gakusei",
      "v-gakkou",
      "v-tomodachi",
      "v-hon",
      "v-nihongo",
      "v-kyou",
      "v-iku",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-reading-2",
    unitId: "unit-integration",
    type: "reading",
    title: "Reading Practice 2",
    description: "Longer passages combining grammar and daily vocabulary",
    order: 98,
    difficulty: 4,
    lessonType: "READING",
    vocabularyIds: [
      "v-kazoku",
      "v-uchi",
      "v-taberu",
      "v-miru",
      "v-eiga",
      "v-suki",
      "v-ashita",
      "v-resutoran",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-listening-1",
    unitId: "unit-integration",
    type: "listening",
    title: "Listening Practice",
    description: "Train your ear with greetings, questions, and simple dialogues",
    order: 99,
    difficulty: 4,
    lessonType: "LISTENING",
    vocabularyIds: [
      "v-konnichiwa",
      "v-ohayou",
      "v-arigatou",
      "v-sumimasen",
      "v-hai",
      "v-iie",
      "v-doko",
      "v-nani",
    ],
    grammarIds: [],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-sentence-building",
    unitId: "unit-integration",
    type: "sentence",
    title: "Sentence Building",
    description: "Assemble complete N5 sentences from words and particles",
    order: 100,
    difficulty: 4,
    lessonType: "SENTENCE_BUILDING",
    vocabularyIds: [
      "v-watashi",
      "v-hon",
      "v-koohii",
      "v-gakkou",
      "v-taberu",
      "v-iku",
      "v-tomodachi",
    ],
    grammarIds: ["g-wo", "g-ni", "g-de", "g-masu"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-translation-practice",
    unitId: "unit-integration",
    type: "sentence",
    title: "Translation Practice",
    description: "Translate both ways between English and Japanese",
    order: 101,
    difficulty: 4,
    lessonType: "TRANSLATION",
    vocabularyIds: [
      "v-watashi",
      "v-sensei",
      "v-nihongo",
      "v-benkyou",
      "v-suki",
      "v-mainichi",
    ],
    grammarIds: ["g-desu", "g-masu", "g-wa"],
    kanjiIds: [],
    kanaIds: [],
  }),
  concept({
    id: "c-mixed-review-n5",
    unitId: "unit-integration",
    type: "grammar",
    title: "N5 Mixed Review",
    description: "Comprehensive review spanning vocabulary, grammar, and kanji",
    order: 102,
    difficulty: 4,
    lessonType: "MIXED_REVIEW",
    vocabularyIds: [
      "v-watashi",
      "v-gakusei",
      "v-iku",
      "v-taberu",
      "v-ookii",
      "v-kirei",
      "v-kyou",
      "v-tomodachi",
    ],
    grammarIds: ["g-desu", "g-masu", "g-te-form", "g-wa", "g-wo"],
    kanjiIds: ["kj-ichi", "kj-hito", "kj-nichi", "kj-hon"],
    kanaIds: [],
  }),
];

/** Linear chain: each concept requires the immediately previous one. */
export const PREREQUISITES: Record<string, string[]> = Object.fromEntries(
  CONCEPTS.slice(1).map((c, i) => [c.id, [CONCEPTS[i].id]])
);

export function getConceptById(id: string): Concept | undefined {
  return CONCEPTS.find((c) => c.id === id);
}

export function getConceptsByUnit(unitId: string): Concept[] {
  return CONCEPTS.filter((c) => c.unitId === unitId).sort(
    (a, b) => a.order - b.order
  );
}

export function getSortedConcepts(): Concept[] {
  return [...CONCEPTS].sort((a, b) => a.order - b.order);
}
