import type { KanjiItem } from "@/lib/types";

export const KANJI: KanjiItem[] = [
  // ── Numbers ──────────────────────────────────────────────
  {
    id: "kj-ichi",
    character: "一",
    meaning: "one",
    onyomi: ["いち"],
    kunyomi: ["ひと"],
    exampleWords: [
      { japanese: "一", reading: "いち", english: "one" },
      { japanese: "一人", reading: "ひとり", english: "one person" },
      { japanese: "一つ", reading: "ひとつ", english: "one (thing)" },
    ],
    category: "numbers",
    exampleSentence: "一人で行きます。",
    exampleSentenceReading: "ひとりでいきます。",
    exampleTranslation: "I will go alone.",
  },
  {
    id: "kj-ni",
    character: "二",
    meaning: "two",
    onyomi: ["に"],
    kunyomi: ["ふた"],
    exampleWords: [
      { japanese: "二", reading: "に", english: "two" },
      { japanese: "二人", reading: "ふたり", english: "two people" },
      { japanese: "二つ", reading: "ふたつ", english: "two (things)" },
    ],
    category: "numbers",
    exampleSentence: "二人が来ました。",
    exampleSentenceReading: "ふたりがきました。",
    exampleTranslation: "Two people came.",
  },
  {
    id: "kj-san",
    character: "三",
    meaning: "three",
    onyomi: ["さん"],
    kunyomi: ["み", "みっ"],
    exampleWords: [
      { japanese: "三", reading: "さん", english: "three" },
      { japanese: "三日", reading: "みっか", english: "third day; three days" },
      { japanese: "三つ", reading: "みっつ", english: "three (things)" },
    ],
    category: "numbers",
    exampleSentence: "三時に会いましょう。",
    exampleSentenceReading: "さんじにあいましょう。",
    exampleTranslation: "Let's meet at three o'clock.",
  },
  {
    id: "kj-shi",
    character: "四",
    meaning: "four",
    onyomi: ["し"],
    kunyomi: ["よ", "よん", "よっ"],
    exampleWords: [
      { japanese: "四", reading: "よん", english: "four" },
      { japanese: "四月", reading: "しがつ", english: "April" },
      { japanese: "四つ", reading: "よっつ", english: "four (things)" },
    ],
    category: "numbers",
    exampleSentence: "四人がいます。",
    exampleSentenceReading: "よにんがいます。",
    exampleTranslation: "There are four people.",
  },
  {
    id: "kj-go",
    character: "五",
    meaning: "five",
    onyomi: ["ご"],
    kunyomi: ["いつ"],
    exampleWords: [
      { japanese: "五", reading: "ご", english: "five" },
      { japanese: "五日", reading: "いつか", english: "fifth day; five days" },
      { japanese: "五つ", reading: "いつつ", english: "five (things)" },
    ],
    category: "numbers",
    exampleSentence: "五分待ってください。",
    exampleSentenceReading: "ごふんまってください。",
    exampleTranslation: "Please wait five minutes.",
  },
  {
    id: "kj-roku",
    character: "六",
    meaning: "six",
    onyomi: ["ろく"],
    kunyomi: ["む", "むっ", "むい"],
    exampleWords: [
      { japanese: "六", reading: "ろく", english: "six" },
      { japanese: "六月", reading: "ろくがつ", english: "June" },
      { japanese: "六つ", reading: "むっつ", english: "six (things)" },
    ],
    category: "numbers",
    exampleSentence: "六時に起きます。",
    exampleSentenceReading: "ろくじにおきます。",
    exampleTranslation: "I wake up at six o'clock.",
  },
  {
    id: "kj-nana",
    character: "七",
    meaning: "seven",
    onyomi: ["しち"],
    kunyomi: ["なな", "なの"],
    exampleWords: [
      { japanese: "七", reading: "なな", english: "seven" },
      { japanese: "七日", reading: "なのか", english: "seventh day; seven days" },
      { japanese: "七つ", reading: "ななつ", english: "seven (things)" },
    ],
    category: "numbers",
    exampleSentence: "七日まで休みです。",
    exampleSentenceReading: "なのかまでやすみです。",
    exampleTranslation: "I'm off until the seventh.",
  },
  {
    id: "kj-hachi",
    character: "八",
    meaning: "eight",
    onyomi: ["はち"],
    kunyomi: ["や", "よう", "やっ"],
    exampleWords: [
      { japanese: "八", reading: "はち", english: "eight" },
      { japanese: "八月", reading: "はちがつ", english: "August" },
      { japanese: "八つ", reading: "やっつ", english: "eight (things)" },
    ],
    category: "numbers",
    exampleSentence: "八時に学校へ行きます。",
    exampleSentenceReading: "はちじにがっこうへいきます。",
    exampleTranslation: "I go to school at eight o'clock.",
  },
  {
    id: "kj-kyuu",
    character: "九",
    meaning: "nine",
    onyomi: ["きゅう", "く"],
    kunyomi: ["ここの"],
    exampleWords: [
      { japanese: "九", reading: "きゅう", english: "nine" },
      { japanese: "九月", reading: "くがつ", english: "September" },
      { japanese: "九つ", reading: "ここのつ", english: "nine (things)" },
    ],
    category: "numbers",
    exampleSentence: "九時から勉強します。",
    exampleSentenceReading: "くじからべんきょうします。",
    exampleTranslation: "I study from nine o'clock.",
  },
  {
    id: "kj-juu",
    character: "十",
    meaning: "ten",
    onyomi: ["じゅう"],
    kunyomi: ["とお", "と"],
    exampleWords: [
      { japanese: "十", reading: "じゅう", english: "ten" },
      { japanese: "十日", reading: "とおか", english: "tenth day; ten days" },
      { japanese: "十人", reading: "じゅうにん", english: "ten people" },
    ],
    category: "numbers",
    exampleSentence: "十日に日本へ行きます。",
    exampleSentenceReading: "とおかににほんへいきます。",
    exampleTranslation: "I go to Japan on the tenth.",
  },
  {
    id: "kj-hyaku",
    character: "百",
    meaning: "hundred",
    onyomi: ["ひゃく"],
    kunyomi: [],
    exampleWords: [
      { japanese: "百", reading: "ひゃく", english: "hundred" },
      { japanese: "三百", reading: "さんびゃく", english: "three hundred" },
      { japanese: "百円", reading: "ひゃくえん", english: "100 yen" },
    ],
    category: "numbers",
    exampleSentence: "これは百円です。",
    exampleSentenceReading: "これはひゃくえんです。",
    exampleTranslation: "This is 100 yen.",
  },
  {
    id: "kj-sen",
    character: "千",
    meaning: "thousand",
    onyomi: ["せん"],
    kunyomi: ["ち"],
    exampleWords: [
      { japanese: "千", reading: "せん", english: "thousand" },
      { japanese: "三千", reading: "さんぜん", english: "three thousand" },
      { japanese: "千円", reading: "せんえん", english: "1,000 yen" },
    ],
    category: "numbers",
    exampleSentence: "本は千円です。",
    exampleSentenceReading: "ほんはせんえんです。",
    exampleTranslation: "The book is 1,000 yen.",
  },
  {
    id: "kj-man",
    character: "万",
    meaning: "ten thousand",
    onyomi: ["まん"],
    kunyomi: [],
    exampleWords: [
      { japanese: "万", reading: "まん", english: "ten thousand" },
      { japanese: "一万円", reading: "いちまんえん", english: "10,000 yen" },
      { japanese: "万人", reading: "まんにん", english: "ten thousand people" },
    ],
    category: "numbers",
    exampleSentence: "一万円あります。",
    exampleSentenceReading: "いちまんえんあります。",
    exampleTranslation: "I have 10,000 yen.",
  },
  {
    id: "kj-en",
    character: "円",
    meaning: "yen; circle",
    onyomi: ["えん"],
    kunyomi: ["まる"],
    exampleWords: [
      { japanese: "円", reading: "えん", english: "yen" },
      { japanese: "百円", reading: "ひゃくえん", english: "100 yen" },
      { japanese: "円い", reading: "まるい", english: "round" },
    ],
    category: "numbers",
    exampleSentence: "このりんごは二百円です。",
    exampleSentenceReading: "このりんごはにひゃくえんです。",
    exampleTranslation: "This apple is 200 yen.",
  },
  {
    id: "kj-han",
    character: "半",
    meaning: "half",
    onyomi: ["はん"],
    kunyomi: ["なか"],
    exampleWords: [
      { japanese: "半分", reading: "はんぶん", english: "half" },
      { japanese: "半", reading: "はん", english: "half (past the hour)" },
      { japanese: "半年", reading: "はんとし", english: "half a year" },
    ],
    category: "numbers",
    exampleSentence: "三時半に来てください。",
    exampleSentenceReading: "さんじはんにきてください。",
    exampleTranslation: "Please come at half past three.",
  },

  // ── Time ─────────────────────────────────────────────────
  {
    id: "kj-nichi",
    character: "日",
    meaning: "day; sun",
    onyomi: ["にち", "じつ"],
    kunyomi: ["ひ", "か"],
    exampleWords: [
      { japanese: "日本", reading: "にほん", english: "Japan" },
      { japanese: "今日", reading: "きょう", english: "today" },
      { japanese: "日曜日", reading: "にちようび", english: "Sunday" },
    ],
    category: "time",
    exampleSentence: "今日は日曜日です。",
    exampleSentenceReading: "きょうはにちようびです。",
    exampleTranslation: "Today is Sunday.",
  },
  {
    id: "kj-getsu",
    character: "月",
    meaning: "month; moon",
    onyomi: ["げつ", "がつ"],
    kunyomi: ["つき"],
    exampleWords: [
      { japanese: "月曜日", reading: "げつようび", english: "Monday" },
      { japanese: "一月", reading: "いちがつ", english: "January" },
      { japanese: "月", reading: "つき", english: "moon" },
    ],
    category: "time",
    exampleSentence: "月曜日に学校へ行きます。",
    exampleSentenceReading: "げつようびにがっこうへいきます。",
    exampleTranslation: "I go to school on Monday.",
  },
  {
    id: "kj-ka",
    character: "火",
    meaning: "fire; Tuesday",
    onyomi: ["か"],
    kunyomi: ["ひ"],
    exampleWords: [
      { japanese: "火曜日", reading: "かようび", english: "Tuesday" },
      { japanese: "花火", reading: "はなび", english: "fireworks" },
      { japanese: "火事", reading: "かじ", english: "fire (disaster)" },
    ],
    category: "time",
    exampleSentence: "火曜日に会いましょう。",
    exampleSentenceReading: "かようびにあいましょう。",
    exampleTranslation: "Let's meet on Tuesday.",
  },
  {
    id: "kj-sui",
    character: "水",
    meaning: "water; Wednesday",
    onyomi: ["すい"],
    kunyomi: ["みず"],
    exampleWords: [
      { japanese: "水曜日", reading: "すいようび", english: "Wednesday" },
      { japanese: "水", reading: "みず", english: "water" },
      { japanese: "水道", reading: "すいどう", english: "water supply" },
    ],
    category: "time",
    exampleSentence: "水を飲んでください。",
    exampleSentenceReading: "みずをのんでください。",
    exampleTranslation: "Please drink water.",
  },
  {
    id: "kj-kin",
    character: "金",
    meaning: "gold; money; Friday",
    onyomi: ["きん", "こん"],
    kunyomi: ["かね"],
    exampleWords: [
      { japanese: "金曜日", reading: "きんようび", english: "Friday" },
      { japanese: "お金", reading: "おかね", english: "money" },
      { japanese: "金", reading: "きん", english: "gold" },
    ],
    category: "time",
    exampleSentence: "金曜日にお金を払います。",
    exampleSentenceReading: "きんようびにおかねをはらいます。",
    exampleTranslation: "I will pay money on Friday.",
  },
  {
    id: "kj-do",
    character: "土",
    meaning: "soil; Saturday",
    onyomi: ["ど", "と"],
    kunyomi: ["つち"],
    exampleWords: [
      { japanese: "土曜日", reading: "どようび", english: "Saturday" },
      { japanese: "土地", reading: "とち", english: "land" },
      { japanese: "土", reading: "つち", english: "soil; dirt" },
    ],
    category: "time",
    exampleSentence: "土曜日は休みです。",
    exampleSentenceReading: "どようびはやすみです。",
    exampleTranslation: "Saturday is a day off.",
  },
  {
    id: "kj-nen",
    character: "年",
    meaning: "year",
    onyomi: ["ねん"],
    kunyomi: ["とし"],
    exampleWords: [
      { japanese: "今年", reading: "ことし", english: "this year" },
      { japanese: "来年", reading: "らいねん", english: "next year" },
      { japanese: "一年", reading: "いちねん", english: "one year" },
    ],
    category: "time",
    exampleSentence: "来年日本へ行きます。",
    exampleSentenceReading: "らいねんにほんへいきます。",
    exampleTranslation: "I will go to Japan next year.",
  },
  {
    id: "kj-ji",
    character: "時",
    meaning: "time; hour",
    onyomi: ["じ"],
    kunyomi: ["とき"],
    exampleWords: [
      { japanese: "一時", reading: "いちじ", english: "one o'clock" },
      { japanese: "時間", reading: "じかん", english: "time; hour" },
      { japanese: "時計", reading: "とけい", english: "clock; watch" },
    ],
    category: "time",
    exampleSentence: "今、何時ですか。",
    exampleSentenceReading: "いま、なんじですか。",
    exampleTranslation: "What time is it now?",
  },
  {
    id: "kj-fun",
    character: "分",
    meaning: "minute; part",
    onyomi: ["ふん", "ぶん", "ぷん"],
    kunyomi: ["わ"],
    exampleWords: [
      { japanese: "五分", reading: "ごふん", english: "five minutes" },
      { japanese: "自分", reading: "じぶん", english: "oneself" },
      { japanese: "分かる", reading: "わかる", english: "to understand" },
    ],
    category: "time",
    exampleSentence: "十分待ってください。",
    exampleSentenceReading: "じゅっぷんまってください。",
    exampleTranslation: "Please wait ten minutes.",
  },
  {
    id: "kj-go-noon",
    character: "午",
    meaning: "noon",
    onyomi: ["ご"],
    kunyomi: [],
    exampleWords: [
      { japanese: "午前", reading: "ごぜん", english: "a.m.; morning" },
      { japanese: "午後", reading: "ごご", english: "p.m.; afternoon" },
      { japanese: "正午", reading: "しょうご", english: "noon" },
    ],
    category: "time",
    exampleSentence: "午後三時に会います。",
    exampleSentenceReading: "ごごさんじにあいます。",
    exampleTranslation: "I will meet at 3 p.m.",
  },
  {
    id: "kj-mae",
    character: "前",
    meaning: "before; in front",
    onyomi: ["ぜん"],
    kunyomi: ["まえ"],
    exampleWords: [
      { japanese: "前", reading: "まえ", english: "before; front" },
      { japanese: "午前", reading: "ごぜん", english: "a.m.; morning" },
      { japanese: "名前", reading: "なまえ", english: "name" },
    ],
    category: "time",
    exampleSentence: "駅の前で待ちます。",
    exampleSentenceReading: "えきのまえでまちます。",
    exampleTranslation: "I will wait in front of the station.",
  },
  {
    id: "kj-ato",
    character: "後",
    meaning: "after; behind",
    onyomi: ["ご", "こう"],
    kunyomi: ["あと", "うし", "のち"],
    exampleWords: [
      { japanese: "後", reading: "あと", english: "after; later" },
      { japanese: "午後", reading: "ごご", english: "p.m.; afternoon" },
      { japanese: "後ろ", reading: "うしろ", english: "behind; back" },
    ],
    category: "time",
    exampleSentence: "ご飯の後で勉強します。",
    exampleSentenceReading: "ごはんのあとでべんきょうします。",
    exampleTranslation: "I study after meals.",
  },
  {
    id: "kj-ima",
    character: "今",
    meaning: "now",
    onyomi: ["こん"],
    kunyomi: ["いま"],
    exampleWords: [
      { japanese: "今", reading: "いま", english: "now" },
      { japanese: "今日", reading: "きょう", english: "today" },
      { japanese: "今週", reading: "こんしゅう", english: "this week" },
    ],
    category: "time",
    exampleSentence: "今、忙しいです。",
    exampleSentenceReading: "いま、いそがしいです。",
    exampleTranslation: "I am busy now.",
  },
  {
    id: "kj-shuu",
    character: "週",
    meaning: "week",
    onyomi: ["しゅう"],
    kunyomi: [],
    exampleWords: [
      { japanese: "今週", reading: "こんしゅう", english: "this week" },
      { japanese: "来週", reading: "らいしゅう", english: "next week" },
      { japanese: "毎週", reading: "まいしゅう", english: "every week" },
    ],
    category: "time",
    exampleSentence: "来週東京へ行きます。",
    exampleSentenceReading: "らいしゅうとうきょうへいきます。",
    exampleTranslation: "I will go to Tokyo next week.",
  },
  {
    id: "kj-mai",
    character: "毎",
    meaning: "every",
    onyomi: ["まい"],
    kunyomi: [],
    exampleWords: [
      { japanese: "毎日", reading: "まいにち", english: "every day" },
      { japanese: "毎朝", reading: "まいあさ", english: "every morning" },
      { japanese: "毎年", reading: "まいとし", english: "every year" },
    ],
    category: "time",
    exampleSentence: "毎日日本語を勉強します。",
    exampleSentenceReading: "まいにちにほんごをべんきょうします。",
    exampleTranslation: "I study Japanese every day.",
  },
  {
    id: "kj-you",
    character: "曜",
    meaning: "day of the week",
    onyomi: ["よう"],
    kunyomi: [],
    exampleWords: [
      { japanese: "曜日", reading: "ようび", english: "day of the week" },
      { japanese: "日曜日", reading: "にちようび", english: "Sunday" },
      { japanese: "何曜日", reading: "なんようび", english: "what day of the week" },
    ],
    category: "time",
    exampleSentence: "今日は何曜日ですか。",
    exampleSentenceReading: "きょうはなんようびですか。",
    exampleTranslation: "What day of the week is it today?",
  },

  // ── People ───────────────────────────────────────────────
  {
    id: "kj-hito",
    character: "人",
    meaning: "person",
    onyomi: ["じん", "にん"],
    kunyomi: ["ひと"],
    exampleWords: [
      { japanese: "人", reading: "ひと", english: "person" },
      { japanese: "日本人", reading: "にほんじん", english: "Japanese person" },
      { japanese: "三人", reading: "さんにん", english: "three people" },
    ],
    category: "people",
    exampleSentence: "あの人は先生です。",
    exampleSentenceReading: "あのひとはせんせいです。",
    exampleTranslation: "That person is a teacher.",
  },
  {
    id: "kj-otoko",
    character: "男",
    meaning: "man; male",
    onyomi: ["だん", "なん"],
    kunyomi: ["おとこ"],
    exampleWords: [
      { japanese: "男", reading: "おとこ", english: "man" },
      { japanese: "男の人", reading: "おとこのひと", english: "man" },
      { japanese: "男子", reading: "だんし", english: "boy; young man" },
    ],
    category: "people",
    exampleSentence: "男の人が来ました。",
    exampleSentenceReading: "おとこのひとがきました。",
    exampleTranslation: "A man came.",
  },
  {
    id: "kj-onna",
    character: "女",
    meaning: "woman; female",
    onyomi: ["じょ", "にょ"],
    kunyomi: ["おんな", "め"],
    exampleWords: [
      { japanese: "女", reading: "おんな", english: "woman" },
      { japanese: "女の人", reading: "おんなのひと", english: "woman" },
      { japanese: "女子", reading: "じょし", english: "girl; young woman" },
    ],
    category: "people",
    exampleSentence: "女の人が話しています。",
    exampleSentenceReading: "おんなのひとがはなしています。",
    exampleTranslation: "A woman is talking.",
  },
  {
    id: "kj-ko",
    character: "子",
    meaning: "child",
    onyomi: ["し", "す"],
    kunyomi: ["こ"],
    exampleWords: [
      { japanese: "子供", reading: "こども", english: "child" },
      { japanese: "椅子", reading: "いす", english: "chair" },
      { japanese: "電子", reading: "でんし", english: "electron; electronic" },
    ],
    category: "people",
    exampleSentence: "子供が公園で遊んでいます。",
    exampleSentenceReading: "こどもがこうえんであそんでいます。",
    exampleTranslation: "Children are playing in the park.",
  },
  {
    id: "kj-chichi",
    character: "父",
    meaning: "father",
    onyomi: ["ふ"],
    kunyomi: ["ちち", "とう"],
    exampleWords: [
      { japanese: "父", reading: "ちち", english: "father (one's own)" },
      { japanese: "お父さん", reading: "おとうさん", english: "father" },
      { japanese: "父母", reading: "ふぼ", english: "father and mother" },
    ],
    category: "people",
    exampleSentence: "父は会社員です。",
    exampleSentenceReading: "ちちはかいしゃいんです。",
    exampleTranslation: "My father is a company employee.",
  },
  {
    id: "kj-haha",
    character: "母",
    meaning: "mother",
    onyomi: ["ぼ"],
    kunyomi: ["はは", "かあ"],
    exampleWords: [
      { japanese: "母", reading: "はは", english: "mother (one's own)" },
      { japanese: "お母さん", reading: "おかあさん", english: "mother" },
      { japanese: "母語", reading: "ぼご", english: "mother tongue" },
    ],
    category: "people",
    exampleSentence: "母は料理が上手です。",
    exampleSentenceReading: "はははりょうりがじょうずです。",
    exampleTranslation: "My mother is good at cooking.",
  },
  {
    id: "kj-tomo",
    character: "友",
    meaning: "friend",
    onyomi: ["ゆう"],
    kunyomi: ["とも"],
    exampleWords: [
      { japanese: "友達", reading: "ともだち", english: "friend" },
      { japanese: "友人", reading: "ゆうじん", english: "friend" },
      { japanese: "親友", reading: "しんゆう", english: "close friend" },
    ],
    category: "people",
    exampleSentence: "友達と映画を見ます。",
    exampleSentenceReading: "ともだちとえいがをみます。",
    exampleTranslation: "I watch a movie with a friend.",
  },
  {
    id: "kj-na",
    character: "名",
    meaning: "name",
    onyomi: ["めい", "みょう"],
    kunyomi: ["な"],
    exampleWords: [
      { japanese: "名前", reading: "なまえ", english: "name" },
      { japanese: "有名", reading: "ゆうめい", english: "famous" },
      { japanese: "名刺", reading: "めいし", english: "business card" },
    ],
    category: "people",
    exampleSentence: "名前を書いてください。",
    exampleSentenceReading: "なまえをかいてください。",
    exampleTranslation: "Please write your name.",
  },
  {
    id: "kj-ani",
    character: "兄",
    meaning: "older brother",
    onyomi: ["けい", "きょう"],
    kunyomi: ["あに"],
    exampleWords: [
      { japanese: "兄", reading: "あに", english: "older brother (one's own)" },
      { japanese: "お兄さん", reading: "おにいさん", english: "older brother" },
      { japanese: "兄弟", reading: "きょうだい", english: "siblings" },
    ],
    category: "people",
    exampleSentence: "兄は大学生です。",
    exampleSentenceReading: "あにはだいがくせいです。",
    exampleTranslation: "My older brother is a university student.",
  },
  {
    id: "kj-ane",
    character: "姉",
    meaning: "older sister",
    onyomi: ["し"],
    kunyomi: ["あね"],
    exampleWords: [
      { japanese: "姉", reading: "あね", english: "older sister (one's own)" },
      { japanese: "お姉さん", reading: "おねえさん", english: "older sister" },
      { japanese: "姉妹", reading: "しまい", english: "sisters" },
    ],
    category: "people",
    exampleSentence: "姉は先生です。",
    exampleSentenceReading: "あねはせんせいです。",
    exampleTranslation: "My older sister is a teacher.",
  },
  {
    id: "kj-otouto",
    character: "弟",
    meaning: "younger brother",
    onyomi: ["てい", "だい"],
    kunyomi: ["おとうと"],
    exampleWords: [
      { japanese: "弟", reading: "おとうと", english: "younger brother" },
      { japanese: "兄弟", reading: "きょうだい", english: "siblings" },
      { japanese: "弟子", reading: "でし", english: "disciple; pupil" },
    ],
    category: "people",
    exampleSentence: "弟は高校生です。",
    exampleSentenceReading: "おとうとはこうこうせいです。",
    exampleTranslation: "My younger brother is a high school student.",
  },
  {
    id: "kj-imouto",
    character: "妹",
    meaning: "younger sister",
    onyomi: ["まい"],
    kunyomi: ["いもうと"],
    exampleWords: [
      { japanese: "妹", reading: "いもうと", english: "younger sister" },
      { japanese: "姉妹", reading: "しまい", english: "sisters" },
    ],
    category: "people",
    exampleSentence: "妹は中学生です。",
    exampleSentenceReading: "いもうとはちゅうがくせいです。",
    exampleTranslation: "My younger sister is a junior high student.",
  },

  // ── Nature ───────────────────────────────────────────────
  {
    id: "kj-yama",
    character: "山",
    meaning: "mountain",
    onyomi: ["さん", "ざん"],
    kunyomi: ["やま"],
    exampleWords: [
      { japanese: "山", reading: "やま", english: "mountain" },
      { japanese: "富士山", reading: "ふじさん", english: "Mt. Fuji" },
      { japanese: "山田", reading: "やまだ", english: "Yamada (surname)" },
    ],
    category: "nature",
    exampleSentence: "山に登ります。",
    exampleSentenceReading: "やまにのぼります。",
    exampleTranslation: "I climb a mountain.",
  },
  {
    id: "kj-kawa",
    character: "川",
    meaning: "river",
    onyomi: ["せん"],
    kunyomi: ["かわ"],
    exampleWords: [
      { japanese: "川", reading: "かわ", english: "river" },
      { japanese: "川口", reading: "かわぐち", english: "river mouth; Kawaguchi" },
    ],
    category: "nature",
    exampleSentence: "川で魚を捕ります。",
    exampleSentenceReading: "かわでさかなをとります。",
    exampleTranslation: "I catch fish in the river.",
  },
  {
    id: "kj-ten",
    character: "天",
    meaning: "heaven; sky",
    onyomi: ["てん"],
    kunyomi: ["あま", "あめ"],
    exampleWords: [
      { japanese: "天気", reading: "てんき", english: "weather" },
      { japanese: "天国", reading: "てんごく", english: "heaven" },
      { japanese: "天気図", reading: "てんきず", english: "weather map" },
    ],
    category: "nature",
    exampleSentence: "今日は天気がいいです。",
    exampleSentenceReading: "きょうはてんきがいいです。",
    exampleTranslation: "The weather is nice today.",
  },
  {
    id: "kj-ki",
    character: "気",
    meaning: "spirit; mind; air",
    onyomi: ["き", "け"],
    kunyomi: [],
    exampleWords: [
      { japanese: "天気", reading: "てんき", english: "weather" },
      { japanese: "元気", reading: "げんき", english: "healthy; energetic" },
      { japanese: "気持ち", reading: "きもち", english: "feeling" },
    ],
    category: "nature",
    exampleSentence: "元気ですか。",
    exampleSentenceReading: "げんきですか。",
    exampleTranslation: "How are you? (Are you well?)",
  },
  {
    id: "kj-ame",
    character: "雨",
    meaning: "rain",
    onyomi: ["う"],
    kunyomi: ["あめ", "あま"],
    exampleWords: [
      { japanese: "雨", reading: "あめ", english: "rain" },
      { japanese: "大雨", reading: "おおあめ", english: "heavy rain" },
      { japanese: "雨天", reading: "うてん", english: "rainy weather" },
    ],
    category: "nature",
    exampleSentence: "今日は雨です。",
    exampleSentenceReading: "きょうはあめです。",
    exampleTranslation: "It is raining today.",
  },
  {
    id: "kj-hana",
    character: "花",
    meaning: "flower",
    onyomi: ["か"],
    kunyomi: ["はな"],
    exampleWords: [
      { japanese: "花", reading: "はな", english: "flower" },
      { japanese: "花火", reading: "はなび", english: "fireworks" },
      { japanese: "花見", reading: "はなみ", english: "cherry blossom viewing" },
    ],
    category: "nature",
    exampleSentence: "きれいな花ですね。",
    exampleSentenceReading: "きれいなはなですね。",
    exampleTranslation: "What a beautiful flower.",
  },
  {
    id: "kj-ki-tree",
    character: "木",
    meaning: "tree; wood",
    onyomi: ["もく", "ぼく"],
    kunyomi: ["き", "こ"],
    exampleWords: [
      { japanese: "木", reading: "き", english: "tree" },
      { japanese: "木曜日", reading: "もくようび", english: "Thursday" },
      { japanese: "木村", reading: "きむら", english: "Kimura (surname)" },
    ],
    category: "nature",
    exampleSentence: "公園に大きい木があります。",
    exampleSentenceReading: "こうえんにおおきいきがあります。",
    exampleTranslation: "There is a big tree in the park.",
  },
  {
    id: "kj-hayashi",
    character: "林",
    meaning: "woods; grove",
    onyomi: ["りん"],
    kunyomi: ["はやし"],
    exampleWords: [
      { japanese: "林", reading: "はやし", english: "woods; grove" },
      { japanese: "森林", reading: "しんりん", english: "forest" },
    ],
    category: "nature",
    exampleSentence: "林の中を歩きます。",
    exampleSentenceReading: "はやしのなかをあるきます。",
    exampleTranslation: "I walk through the woods.",
  },
  {
    id: "kj-mori",
    character: "森",
    meaning: "forest",
    onyomi: ["しん"],
    kunyomi: ["もり"],
    exampleWords: [
      { japanese: "森", reading: "もり", english: "forest" },
      { japanese: "森林", reading: "しんりん", english: "forest" },
    ],
    category: "nature",
    exampleSentence: "森で鳥の声を聞きます。",
    exampleSentenceReading: "もりでとりのこえをききます。",
    exampleTranslation: "I hear birdsong in the forest.",
  },
  {
    id: "kj-umi",
    character: "海",
    meaning: "sea; ocean",
    onyomi: ["かい"],
    kunyomi: ["うみ"],
    exampleWords: [
      { japanese: "海", reading: "うみ", english: "sea; ocean" },
      { japanese: "海外", reading: "かいがい", english: "overseas" },
      { japanese: "北海道", reading: "ほっかいどう", english: "Hokkaido" },
    ],
    category: "nature",
    exampleSentence: "夏に海へ行きます。",
    exampleSentenceReading: "なつにうみへいきます。",
    exampleTranslation: "I go to the sea in summer.",
  },
  {
    id: "kj-sora",
    character: "空",
    meaning: "sky; empty",
    onyomi: ["くう"],
    kunyomi: ["そら", "あ", "から"],
    exampleWords: [
      { japanese: "空", reading: "そら", english: "sky" },
      { japanese: "空港", reading: "くうこう", english: "airport" },
      { japanese: "空く", reading: "あく", english: "to become empty; to open" },
    ],
    category: "nature",
    exampleSentence: "空が青いです。",
    exampleSentenceReading: "そらがあおいです。",
    exampleTranslation: "The sky is blue.",
  },

  // ── Places ───────────────────────────────────────────────
  {
    id: "kj-kou",
    character: "校",
    meaning: "school",
    onyomi: ["こう"],
    kunyomi: [],
    exampleWords: [
      { japanese: "学校", reading: "がっこう", english: "school" },
      { japanese: "高校", reading: "こうこう", english: "high school" },
      { japanese: "校長", reading: "こうちょう", english: "principal" },
    ],
    category: "places",
    exampleSentence: "学校は駅の近くです。",
    exampleSentenceReading: "がっこうはえきのちかくです。",
    exampleTranslation: "The school is near the station.",
  },
  {
    id: "kj-sha",
    character: "社",
    meaning: "company; shrine",
    onyomi: ["しゃ"],
    kunyomi: ["やしろ"],
    exampleWords: [
      { japanese: "会社", reading: "かいしゃ", english: "company" },
      { japanese: "社長", reading: "しゃちょう", english: "company president" },
      { japanese: "社会", reading: "しゃかい", english: "society" },
    ],
    category: "places",
    exampleSentence: "父は会社で働いています。",
    exampleSentenceReading: "ちちはかいしゃではたらいています。",
    exampleTranslation: "My father works at a company.",
  },
  {
    id: "kj-mise",
    character: "店",
    meaning: "shop; store",
    onyomi: ["てん"],
    kunyomi: ["みせ"],
    exampleWords: [
      { japanese: "店", reading: "みせ", english: "shop; store" },
      { japanese: "店員", reading: "てんいん", english: "shop clerk" },
      { japanese: "喫茶店", reading: "きっさてん", english: "coffee shop" },
    ],
    category: "places",
    exampleSentence: "この店は安いです。",
    exampleSentenceReading: "このみせはやすいです。",
    exampleTranslation: "This shop is inexpensive.",
  },
  {
    id: "kj-eki",
    character: "駅",
    meaning: "station",
    onyomi: ["えき"],
    kunyomi: [],
    exampleWords: [
      { japanese: "駅", reading: "えき", english: "station" },
      { japanese: "駅前", reading: "えきまえ", english: "in front of the station" },
      { japanese: "東京駅", reading: "とうきょうえき", english: "Tokyo Station" },
    ],
    category: "places",
    exampleSentence: "駅で友達を待ちます。",
    exampleSentenceReading: "えきでともだちをまちます。",
    exampleTranslation: "I wait for my friend at the station.",
  },
  {
    id: "kj-kuni",
    character: "国",
    meaning: "country",
    onyomi: ["こく"],
    kunyomi: ["くに"],
    exampleWords: [
      { japanese: "国", reading: "くに", english: "country" },
      { japanese: "中国", reading: "ちゅうごく", english: "China" },
      { japanese: "外国", reading: "がいこく", english: "foreign country" },
    ],
    category: "places",
    exampleSentence: "日本はいい国です。",
    exampleSentenceReading: "にほんはいいくにです。",
    exampleTranslation: "Japan is a good country.",
  },
  {
    id: "kj-soto",
    character: "外",
    meaning: "outside",
    onyomi: ["がい", "げ"],
    kunyomi: ["そと", "はず", "ほか"],
    exampleWords: [
      { japanese: "外", reading: "そと", english: "outside" },
      { japanese: "外国", reading: "がいこく", english: "foreign country" },
      { japanese: "外国人", reading: "がいこくじん", english: "foreigner" },
    ],
    category: "places",
    exampleSentence: "外は寒いです。",
    exampleSentenceReading: "そとはさむいです。",
    exampleTranslation: "It is cold outside.",
  },
  {
    id: "kj-kyou",
    character: "京",
    meaning: "capital",
    onyomi: ["きょう", "けい"],
    kunyomi: ["みやこ"],
    exampleWords: [
      { japanese: "東京", reading: "とうきょう", english: "Tokyo" },
      { japanese: "京都", reading: "きょうと", english: "Kyoto" },
      { japanese: "京阪", reading: "けいはん", english: "Kyoto-Osaka (area)" },
    ],
    category: "places",
    exampleSentence: "東京に住んでいます。",
    exampleSentenceReading: "とうきょうにすんでいます。",
    exampleTranslation: "I live in Tokyo.",
  },
  {
    id: "kj-higashi",
    character: "東",
    meaning: "east",
    onyomi: ["とう"],
    kunyomi: ["ひがし"],
    exampleWords: [
      { japanese: "東", reading: "ひがし", english: "east" },
      { japanese: "東京", reading: "とうきょう", english: "Tokyo" },
      { japanese: "関東", reading: "かんとう", english: "Kanto region" },
    ],
    category: "places",
    exampleSentence: "東口で会いましょう。",
    exampleSentenceReading: "ひがしぐちであいましょう。",
    exampleTranslation: "Let's meet at the east exit.",
  },
  {
    id: "kj-nishi",
    character: "西",
    meaning: "west",
    onyomi: ["せい", "さい"],
    kunyomi: ["にし"],
    exampleWords: [
      { japanese: "西", reading: "にし", english: "west" },
      { japanese: "関西", reading: "かんさい", english: "Kansai region" },
      { japanese: "西口", reading: "にしぐち", english: "west exit" },
    ],
    category: "places",
    exampleSentence: "西の空が赤いです。",
    exampleSentenceReading: "にしのそらがあかいです。",
    exampleTranslation: "The western sky is red.",
  },
  {
    id: "kj-minami",
    character: "南",
    meaning: "south",
    onyomi: ["なん"],
    kunyomi: ["みなみ"],
    exampleWords: [
      { japanese: "南", reading: "みなみ", english: "south" },
      { japanese: "南口", reading: "みなみぐち", english: "south exit" },
      { japanese: "南北", reading: "なんぼく", english: "north and south" },
    ],
    category: "places",
    exampleSentence: "南口にあります。",
    exampleSentenceReading: "みなみぐちにあります。",
    exampleTranslation: "It is at the south exit.",
  },
  {
    id: "kj-kita",
    character: "北",
    meaning: "north",
    onyomi: ["ほく"],
    kunyomi: ["きた"],
    exampleWords: [
      { japanese: "北", reading: "きた", english: "north" },
      { japanese: "北海道", reading: "ほっかいどう", english: "Hokkaido" },
      { japanese: "北口", reading: "きたぐち", english: "north exit" },
    ],
    category: "places",
    exampleSentence: "北は寒いです。",
    exampleSentenceReading: "きたはさむいです。",
    exampleTranslation: "The north is cold.",
  },
  {
    id: "kj-machi",
    character: "町",
    meaning: "town",
    onyomi: ["ちょう"],
    kunyomi: ["まち"],
    exampleWords: [
      { japanese: "町", reading: "まち", english: "town" },
      { japanese: "町中", reading: "まちなか", english: "downtown; in town" },
      { japanese: "下町", reading: "したまち", english: "downtown (old district)" },
    ],
    category: "places",
    exampleSentence: "この町は静かです。",
    exampleSentenceReading: "このまちはしずかです。",
    exampleTranslation: "This town is quiet.",
  },
  {
    id: "kj-shi-city",
    character: "市",
    meaning: "city",
    onyomi: ["し"],
    kunyomi: ["いち"],
    exampleWords: [
      { japanese: "市", reading: "し", english: "city" },
      { japanese: "市場", reading: "いちば", english: "market" },
      { japanese: "市民", reading: "しみん", english: "citizen" },
    ],
    category: "places",
    exampleSentence: "大阪市に住んでいます。",
    exampleSentenceReading: "おおさかしにすんでいます。",
    exampleTranslation: "I live in Osaka City.",
  },
  {
    id: "kj-ie",
    character: "家",
    meaning: "house; home",
    onyomi: ["か", "け"],
    kunyomi: ["いえ", "や"],
    exampleWords: [
      { japanese: "家", reading: "いえ", english: "house; home" },
      { japanese: "家族", reading: "かぞく", english: "family" },
      { japanese: "家庭", reading: "かてい", english: "home; household" },
    ],
    category: "places",
    exampleSentence: "六時に家へ帰ります。",
    exampleSentenceReading: "ろくじにいえへかえります。",
    exampleTranslation: "I go home at six o'clock.",
  },

  // ── Daily ────────────────────────────────────────────────
  {
    id: "kj-hon",
    character: "本",
    meaning: "book; origin",
    onyomi: ["ほん"],
    kunyomi: ["もと"],
    exampleWords: [
      { japanese: "本", reading: "ほん", english: "book" },
      { japanese: "日本", reading: "にほん", english: "Japan" },
      { japanese: "本当", reading: "ほんとう", english: "truth; really" },
    ],
    category: "daily",
    exampleSentence: "本を読みます。",
    exampleSentenceReading: "ほんをよみます。",
    exampleTranslation: "I read a book.",
  },
  {
    id: "kj-go-lang",
    character: "語",
    meaning: "language; word",
    onyomi: ["ご"],
    kunyomi: ["かた"],
    exampleWords: [
      { japanese: "日本語", reading: "にほんご", english: "Japanese language" },
      { japanese: "英語", reading: "えいご", english: "English" },
      { japanese: "物語", reading: "ものがたり", english: "story; tale" },
    ],
    category: "daily",
    exampleSentence: "日本語を勉強しています。",
    exampleSentenceReading: "にほんごをべんきょうしています。",
    exampleTranslation: "I am studying Japanese.",
  },
  {
    id: "kj-bun",
    character: "文",
    meaning: "sentence; writing",
    onyomi: ["ぶん", "もん"],
    kunyomi: ["ふみ"],
    exampleWords: [
      { japanese: "文化", reading: "ぶんか", english: "culture" },
      { japanese: "文字", reading: "もじ", english: "letter; character" },
      { japanese: "作文", reading: "さくぶん", english: "composition; essay" },
    ],
    category: "daily",
    exampleSentence: "この文を読んでください。",
    exampleSentenceReading: "このぶんをよんでください。",
    exampleTranslation: "Please read this sentence.",
  },
  {
    id: "kj-ji-char",
    character: "字",
    meaning: "character; letter",
    onyomi: ["じ"],
    kunyomi: ["あざ"],
    exampleWords: [
      { japanese: "文字", reading: "もじ", english: "letter; character" },
      { japanese: "漢字", reading: "かんじ", english: "kanji" },
      { japanese: "字", reading: "じ", english: "character; handwriting" },
    ],
    category: "daily",
    exampleSentence: "漢字は難しいです。",
    exampleSentenceReading: "かんじはむずかしいです。",
    exampleTranslation: "Kanji is difficult.",
  },
  {
    id: "kj-gaku",
    character: "学",
    meaning: "study; learning",
    onyomi: ["がく"],
    kunyomi: ["まな"],
    exampleWords: [
      { japanese: "学校", reading: "がっこう", english: "school" },
      { japanese: "学生", reading: "がくせい", english: "student" },
      { japanese: "大学", reading: "だいがく", english: "university" },
    ],
    category: "daily",
    exampleSentence: "日本語を学んでいます。",
    exampleSentenceReading: "にほんごをまなんでいます。",
    exampleTranslation: "I am learning Japanese.",
  },
  {
    id: "kj-sei",
    character: "生",
    meaning: "life; birth; student",
    onyomi: ["せい", "しょう"],
    kunyomi: ["い", "う", "なま", "き"],
    exampleWords: [
      { japanese: "学生", reading: "がくせい", english: "student" },
      { japanese: "先生", reading: "せんせい", english: "teacher" },
      { japanese: "生まれる", reading: "うまれる", english: "to be born" },
    ],
    category: "daily",
    exampleSentence: "私は学生です。",
    exampleSentenceReading: "わたしはがくせいです。",
    exampleTranslation: "I am a student.",
  },
  {
    id: "kj-nani",
    character: "何",
    meaning: "what",
    onyomi: ["か"],
    kunyomi: ["なに", "なん"],
    exampleWords: [
      { japanese: "何", reading: "なに", english: "what" },
      { japanese: "何人", reading: "なんにん", english: "how many people" },
      { japanese: "何時", reading: "なんじ", english: "what time" },
    ],
    category: "daily",
    exampleSentence: "これは何ですか。",
    exampleSentenceReading: "これはなんですか。",
    exampleTranslation: "What is this?",
  },
  {
    id: "kj-watashi",
    character: "私",
    meaning: "I; private",
    onyomi: ["し"],
    kunyomi: ["わたし", "わたくし"],
    exampleWords: [
      { japanese: "私", reading: "わたし", english: "I; me" },
      { japanese: "私立", reading: "しりつ", english: "private (institution)" },
    ],
    category: "daily",
    exampleSentence: "私は日本人です。",
    exampleSentenceReading: "わたしはにほんじんです。",
    exampleTranslation: "I am Japanese.",
  },
  {
    id: "kj-den",
    character: "電",
    meaning: "electricity",
    onyomi: ["でん"],
    kunyomi: [],
    exampleWords: [
      { japanese: "電車", reading: "でんしゃ", english: "train" },
      { japanese: "電話", reading: "でんわ", english: "telephone" },
      { japanese: "電気", reading: "でんき", english: "electricity; light" },
    ],
    category: "daily",
    exampleSentence: "電車で学校へ行きます。",
    exampleSentenceReading: "でんしゃでがっこうへいきます。",
    exampleTranslation: "I go to school by train.",
  },
  {
    id: "kj-kuruma",
    character: "車",
    meaning: "car; vehicle",
    onyomi: ["しゃ"],
    kunyomi: ["くるま"],
    exampleWords: [
      { japanese: "車", reading: "くるま", english: "car" },
      { japanese: "電車", reading: "でんしゃ", english: "train" },
      { japanese: "自動車", reading: "じどうしゃ", english: "automobile" },
    ],
    category: "daily",
    exampleSentence: "車で行きます。",
    exampleSentenceReading: "くるまでいきます。",
    exampleTranslation: "I will go by car.",
  },
  {
    id: "kj-aida",
    character: "間",
    meaning: "interval; between; space",
    onyomi: ["かん", "けん"],
    kunyomi: ["あいだ", "ま"],
    exampleWords: [
      { japanese: "時間", reading: "じかん", english: "time" },
      { japanese: "間", reading: "あいだ", english: "between; during" },
      { japanese: "人間", reading: "にんげん", english: "human being" },
    ],
    category: "daily",
    exampleSentence: "二時と三時の間に来てください。",
    exampleSentenceReading: "にじとさんじのあいだにきてください。",
    exampleTranslation: "Please come between two and three o'clock.",
  },
  {
    id: "kj-ue",
    character: "上",
    meaning: "up; above",
    onyomi: ["じょう"],
    kunyomi: ["うえ", "あ", "のぼ"],
    exampleWords: [
      { japanese: "上", reading: "うえ", english: "above; on top" },
      { japanese: "上手", reading: "じょうず", english: "skillful" },
      { japanese: "上げる", reading: "あげる", english: "to raise; to give" },
    ],
    category: "daily",
    exampleSentence: "机の上に本があります。",
    exampleSentenceReading: "つくえのうえにほんがあります。",
    exampleTranslation: "There is a book on the desk.",
  },
  {
    id: "kj-shita",
    character: "下",
    meaning: "down; below",
    onyomi: ["か", "げ"],
    kunyomi: ["した", "しも", "さ", "くだ"],
    exampleWords: [
      { japanese: "下", reading: "した", english: "below; under" },
      { japanese: "下手", reading: "へた", english: "unskillful" },
      { japanese: "地下", reading: "ちか", english: "underground" },
    ],
    category: "daily",
    exampleSentence: "椅子の下に猫がいます。",
    exampleSentenceReading: "いすのしたにねこがいます。",
    exampleTranslation: "There is a cat under the chair.",
  },
  {
    id: "kj-hidari",
    character: "左",
    meaning: "left",
    onyomi: ["さ"],
    kunyomi: ["ひだり"],
    exampleWords: [
      { japanese: "左", reading: "ひだり", english: "left" },
      { japanese: "左手", reading: "ひだりて", english: "left hand" },
      { japanese: "左右", reading: "さゆう", english: "left and right" },
    ],
    category: "daily",
    exampleSentence: "左に曲がってください。",
    exampleSentenceReading: "ひだりにまがってください。",
    exampleTranslation: "Please turn left.",
  },
  {
    id: "kj-migi",
    character: "右",
    meaning: "right",
    onyomi: ["う", "ゆう"],
    kunyomi: ["みぎ"],
    exampleWords: [
      { japanese: "右", reading: "みぎ", english: "right" },
      { japanese: "右手", reading: "みぎて", english: "right hand" },
      { japanese: "左右", reading: "さゆう", english: "left and right" },
    ],
    category: "daily",
    exampleSentence: "右の方を見てください。",
    exampleSentenceReading: "みぎのほうをみてください。",
    exampleTranslation: "Please look to the right.",
  },
  {
    id: "kj-naka",
    character: "中",
    meaning: "middle; inside; China",
    onyomi: ["ちゅう"],
    kunyomi: ["なか"],
    exampleWords: [
      { japanese: "中", reading: "なか", english: "inside; middle" },
      { japanese: "中国", reading: "ちゅうごく", english: "China" },
      { japanese: "中学生", reading: "ちゅうがくせい", english: "junior high student" },
    ],
    category: "daily",
    exampleSentence: "箱の中に何がありますか。",
    exampleSentenceReading: "はこのなかになにがありますか。",
    exampleTranslation: "What is inside the box?",
  },

  // ── Adjectives ───────────────────────────────────────────
  {
    id: "kj-yasui",
    character: "安",
    meaning: "cheap; peaceful",
    onyomi: ["あん"],
    kunyomi: ["やす"],
    exampleWords: [
      { japanese: "安い", reading: "やすい", english: "cheap; inexpensive" },
      { japanese: "安心", reading: "あんしん", english: "relief; peace of mind" },
      { japanese: "安全", reading: "あんぜん", english: "safety" },
    ],
    category: "adjectives",
    exampleSentence: "この店は安いです。",
    exampleSentenceReading: "このみせはやすいです。",
    exampleTranslation: "This shop is inexpensive.",
  },
  {
    id: "kj-taka",
    character: "高",
    meaning: "high; expensive",
    onyomi: ["こう"],
    kunyomi: ["たか"],
    exampleWords: [
      { japanese: "高い", reading: "たかい", english: "high; expensive" },
      { japanese: "高校", reading: "こうこう", english: "high school" },
      { japanese: "最高", reading: "さいこう", english: "the best; highest" },
    ],
    category: "adjectives",
    exampleSentence: "この時計は高いです。",
    exampleSentenceReading: "このとけいはたかいです。",
    exampleTranslation: "This watch is expensive.",
  },
  {
    id: "kj-chiisai",
    character: "小",
    meaning: "small",
    onyomi: ["しょう"],
    kunyomi: ["ちい", "こ", "お"],
    exampleWords: [
      { japanese: "小さい", reading: "ちいさい", english: "small" },
      { japanese: "小学校", reading: "しょうがっこう", english: "elementary school" },
      { japanese: "小鳥", reading: "ことり", english: "small bird" },
    ],
    category: "adjectives",
    exampleSentence: "小さい犬がいます。",
    exampleSentenceReading: "ちいさいいぬがいます。",
    exampleTranslation: "There is a small dog.",
  },
  {
    id: "kj-ookii",
    character: "大",
    meaning: "big; large",
    onyomi: ["だい", "たい"],
    kunyomi: ["おお"],
    exampleWords: [
      { japanese: "大きい", reading: "おおきい", english: "big; large" },
      { japanese: "大学", reading: "だいがく", english: "university" },
      { japanese: "大切", reading: "たいせつ", english: "important" },
    ],
    category: "adjectives",
    exampleSentence: "大きい家に住んでいます。",
    exampleSentenceReading: "おおきいいえにすんでいます。",
    exampleTranslation: "I live in a big house.",
  },
  // ── Verbs ────────────────────────────────────────────────
  {
    id: "kj-iku",
    character: "行",
    meaning: "go",
    onyomi: ["こう", "ぎょう"],
    kunyomi: ["い", "ゆ", "おこな"],
    exampleWords: [
      { japanese: "行く", reading: "いく", english: "to go" },
      { japanese: "銀行", reading: "ぎんこう", english: "bank" },
      { japanese: "旅行", reading: "りょこう", english: "travel; trip" },
    ],
    category: "verbs",
    exampleSentence: "明日学校へ行きます。",
    exampleSentenceReading: "あしたがっこうへいきます。",
    exampleTranslation: "I will go to school tomorrow.",
  },
  {
    id: "kj-kuru",
    character: "来",
    meaning: "come",
    onyomi: ["らい"],
    kunyomi: ["く", "き", "こ"],
    exampleWords: [
      { japanese: "来る", reading: "くる", english: "to come" },
      { japanese: "来年", reading: "らいねん", english: "next year" },
      { japanese: "来週", reading: "らいしゅう", english: "next week" },
    ],
    category: "verbs",
    exampleSentence: "友だちが家に来ます。",
    exampleSentenceReading: "ともだちがいえにきます。",
    exampleTranslation: "A friend is coming to my house.",
  },
  {
    id: "kj-taberu",
    character: "食",
    meaning: "eat",
    onyomi: ["しょく"],
    kunyomi: ["た", "く"],
    exampleWords: [
      { japanese: "食べる", reading: "たべる", english: "to eat" },
      { japanese: "食事", reading: "しょくじ", english: "meal" },
      { japanese: "食堂", reading: "しょくどう", english: "cafeteria; dining hall" },
    ],
    category: "verbs",
    exampleSentence: "朝ごはんを食べます。",
    exampleSentenceReading: "あさごはんをたべます。",
    exampleTranslation: "I eat breakfast.",
  },
  {
    id: "kj-nomu",
    character: "飲",
    meaning: "drink",
    onyomi: ["いん"],
    kunyomi: ["の"],
    exampleWords: [
      { japanese: "飲む", reading: "のむ", english: "to drink" },
      { japanese: "飲み物", reading: "のみもの", english: "beverage" },
      { japanese: "飲食", reading: "いんしょく", english: "food and drink" },
    ],
    category: "verbs",
    exampleSentence: "水を飲みます。",
    exampleSentenceReading: "みずをのみます。",
    exampleTranslation: "I drink water.",
  },
  {
    id: "kj-miru",
    character: "見",
    meaning: "see; look",
    onyomi: ["けん"],
    kunyomi: ["み"],
    exampleWords: [
      { japanese: "見る", reading: "みる", english: "to see; to watch" },
      { japanese: "見せる", reading: "みせる", english: "to show" },
      { japanese: "意見", reading: "いけん", english: "opinion" },
    ],
    category: "verbs",
    exampleSentence: "テレビを見ます。",
    exampleSentenceReading: "テレビをみます。",
    exampleTranslation: "I watch television.",
  },
  {
    id: "kj-kiku",
    character: "聞",
    meaning: "hear; ask",
    onyomi: ["ぶん", "もん"],
    kunyomi: ["き"],
    exampleWords: [
      { japanese: "聞く", reading: "きく", english: "to hear; to ask" },
      { japanese: "新聞", reading: "しんぶん", english: "newspaper" },
      { japanese: "聞こえる", reading: "きこえる", english: "to be audible" },
    ],
    category: "verbs",
    exampleSentence: "音楽を聞きます。",
    exampleSentenceReading: "おんがくをききます。",
    exampleTranslation: "I listen to music.",
  },
  {
    id: "kj-yomu",
    character: "読",
    meaning: "read",
    onyomi: ["どく", "とく"],
    kunyomi: ["よ"],
    exampleWords: [
      { japanese: "読む", reading: "よむ", english: "to read" },
      { japanese: "読書", reading: "どくしょ", english: "reading (books)" },
      { japanese: "読み方", reading: "よみかた", english: "way of reading" },
    ],
    category: "verbs",
    exampleSentence: "毎日新聞を読みます。",
    exampleSentenceReading: "まいにちしんぶんをよみます。",
    exampleTranslation: "I read the newspaper every day.",
  },
  {
    id: "kj-kaku",
    character: "書",
    meaning: "write",
    onyomi: ["しょ"],
    kunyomi: ["か"],
    exampleWords: [
      { japanese: "書く", reading: "かく", english: "to write" },
      { japanese: "辞書", reading: "じしょ", english: "dictionary" },
      { japanese: "教科書", reading: "きょうかしょ", english: "textbook" },
    ],
    category: "verbs",
    exampleSentence: "手紙を書きます。",
    exampleSentenceReading: "てがみをかきます。",
    exampleTranslation: "I write a letter.",
  },
  {
    id: "kj-hanasu",
    character: "話",
    meaning: "talk; story",
    onyomi: ["わ"],
    kunyomi: ["はな", "はなし"],
    exampleWords: [
      { japanese: "話す", reading: "はなす", english: "to speak; to talk" },
      { japanese: "話", reading: "はなし", english: "story; talk" },
      { japanese: "電話", reading: "でんわ", english: "telephone" },
    ],
    category: "verbs",
    exampleSentence: "日本語で話します。",
    exampleSentenceReading: "にほんごではなします。",
    exampleTranslation: "I speak in Japanese.",
  },
  {
    id: "kj-kau",
    character: "買",
    meaning: "buy",
    onyomi: ["ばい"],
    kunyomi: ["か"],
    exampleWords: [
      { japanese: "買う", reading: "かう", english: "to buy" },
      { japanese: "買い物", reading: "かいもの", english: "shopping" },
      { japanese: "売買", reading: "ばいばい", english: "buying and selling" },
    ],
    category: "verbs",
    exampleSentence: "店でパンを買います。",
    exampleSentenceReading: "みせでパンをかいます。",
    exampleTranslation: "I buy bread at the store.",
  },
  {
    id: "kj-iru",
    character: "入",
    meaning: "enter; put in",
    onyomi: ["にゅう"],
    kunyomi: ["はい", "い"],
    exampleWords: [
      { japanese: "入る", reading: "はいる", english: "to enter" },
      { japanese: "入れる", reading: "いれる", english: "to put in" },
      { japanese: "入学", reading: "にゅうがく", english: "school admission" },
    ],
    category: "verbs",
    exampleSentence: "教室に入ります。",
    exampleSentenceReading: "きょうしつにはいります。",
    exampleTranslation: "I enter the classroom.",
  },
  {
    id: "kj-deru",
    character: "出",
    meaning: "exit; leave",
    onyomi: ["しゅつ"],
    kunyomi: ["で", "だ"],
    exampleWords: [
      { japanese: "出る", reading: "でる", english: "to leave; to come out" },
      { japanese: "出す", reading: "だす", english: "to take out; to put out" },
      { japanese: "出口", reading: "でぐち", english: "exit" },
    ],
    category: "verbs",
    exampleSentence: "家を出ます。",
    exampleSentenceReading: "いえをでます。",
    exampleTranslation: "I leave the house.",
  },
  {
    id: "kj-yasumu",
    character: "休",
    meaning: "rest; take a break",
    onyomi: ["きゅう"],
    kunyomi: ["やす"],
    exampleWords: [
      { japanese: "休む", reading: "やすむ", english: "to rest; to take a day off" },
      { japanese: "休み", reading: "やすみ", english: "rest; holiday" },
      { japanese: "休日", reading: "きゅうじつ", english: "holiday" },
    ],
    category: "verbs",
    exampleSentence: "日曜日は休みます。",
    exampleSentenceReading: "にちようびはやすみます。",
    exampleTranslation: "I take Sunday off.",
  },
  {
    id: "kj-au",
    character: "会",
    meaning: "meet",
    onyomi: ["かい", "え"],
    kunyomi: ["あ"],
    exampleWords: [
      { japanese: "会う", reading: "あう", english: "to meet" },
      { japanese: "会社", reading: "かいしゃ", english: "company" },
      { japanese: "会議", reading: "かいぎ", english: "meeting; conference" },
    ],
    category: "verbs",
    exampleSentence: "駅で友達に会います。",
    exampleSentenceReading: "えきでともだちにあいます。",
    exampleTranslation: "I meet my friend at the station.",
  },
  {
    id: "kj-kaeru",
    character: "帰",
    meaning: "return home",
    onyomi: ["き"],
    kunyomi: ["かえ"],
    exampleWords: [
      { japanese: "帰る", reading: "かえる", english: "to return home" },
      { japanese: "帰国", reading: "きこく", english: "return to one's country" },
      { japanese: "帰り道", reading: "かえりみち", english: "way home" },
    ],
    category: "verbs",
    exampleSentence: "五時に家へ帰ります。",
    exampleSentenceReading: "ごじにいえへかえります。",
    exampleTranslation: "I return home at five o'clock.",
  },

  // ── Body ─────────────────────────────────────────────────
  {
    id: "kj-mimi",
    character: "耳",
    meaning: "ear",
    onyomi: ["じ"],
    kunyomi: ["みみ"],
    exampleWords: [
      { japanese: "耳", reading: "みみ", english: "ear" },
      { japanese: "耳鼻科", reading: "じびか", english: "ENT (ear-nose-throat)" },
    ],
    category: "body",
    exampleSentence: "耳が痛いです。",
    exampleSentenceReading: "みみがいたいです。",
    exampleTranslation: "My ear hurts.",
  },
  {
    id: "kj-me",
    character: "目",
    meaning: "eye",
    onyomi: ["もく"],
    kunyomi: ["め"],
    exampleWords: [
      { japanese: "目", reading: "め", english: "eye" },
      { japanese: "一目", reading: "ひとめ", english: "a glance" },
      { japanese: "目的", reading: "もくてき", english: "purpose; goal" },
    ],
    category: "body",
    exampleSentence: "目が大きいです。",
    exampleSentenceReading: "めがおおきいです。",
    exampleTranslation: "The eyes are big.",
  },
  {
    id: "kj-kuchi",
    character: "口",
    meaning: "mouth",
    onyomi: ["こう", "く"],
    kunyomi: ["くち"],
    exampleWords: [
      { japanese: "口", reading: "くち", english: "mouth" },
      { japanese: "人口", reading: "じんこう", english: "population" },
      { japanese: "入口", reading: "いりぐち", english: "entrance" },
    ],
    category: "body",
    exampleSentence: "口を開けてください。",
    exampleSentenceReading: "くちをあけてください。",
    exampleTranslation: "Please open your mouth.",
  },
  {
    id: "kj-te",
    character: "手",
    meaning: "hand",
    onyomi: ["しゅ", "ず"],
    kunyomi: ["て"],
    exampleWords: [
      { japanese: "手", reading: "て", english: "hand" },
      { japanese: "上手", reading: "じょうず", english: "skillful" },
      { japanese: "手紙", reading: "てがみ", english: "letter" },
    ],
    category: "body",
    exampleSentence: "手を洗ってください。",
    exampleSentenceReading: "てをあらってください。",
    exampleTranslation: "Please wash your hands.",
  },
  {
    id: "kj-ashi",
    character: "足",
    meaning: "foot; leg",
    onyomi: ["そく"],
    kunyomi: ["あし", "た"],
    exampleWords: [
      { japanese: "足", reading: "あし", english: "foot; leg" },
      { japanese: "足りる", reading: "たりる", english: "to be enough" },
      { japanese: "足音", reading: "あしおと", english: "footsteps" },
    ],
    category: "body",
    exampleSentence: "足が痛いです。",
    exampleSentenceReading: "あしがいたいです。",
    exampleTranslation: "My foot hurts.",
  },

  // ── School ───────────────────────────────────────────────
  {
    id: "kj-saki",
    character: "先",
    meaning: "ahead; previous; tip",
    onyomi: ["せん"],
    kunyomi: ["さき", "ま"],
    exampleWords: [
      { japanese: "先生", reading: "せんせい", english: "teacher" },
      { japanese: "先週", reading: "せんしゅう", english: "last week" },
      { japanese: "先", reading: "さき", english: "ahead; tip; future" },
    ],
    category: "school",
    exampleSentence: "先生は教室にいます。",
    exampleSentenceReading: "せんせいはきょうしつにいます。",
    exampleTranslation: "The teacher is in the classroom.",
  },
  {
    id: "kj-oshieru",
    character: "教",
    meaning: "teach",
    onyomi: ["きょう"],
    kunyomi: ["おし", "おそ"],
    exampleWords: [
      { japanese: "教える", reading: "おしえる", english: "to teach" },
      { japanese: "教室", reading: "きょうしつ", english: "classroom" },
      { japanese: "教科書", reading: "きょうかしょ", english: "textbook" },
    ],
    category: "school",
    exampleSentence: "先生が日本語を教えます。",
    exampleSentenceReading: "せんせいがにほんごをおしえます。",
    exampleTranslation: "The teacher teaches Japanese.",
  },
];

export function getKanjiById(id: string): KanjiItem | undefined {
  return KANJI.find((k) => k.id === id);
}

export function getKanjiByCategory(category: string): KanjiItem[] {
  return KANJI.filter((k) => k.category === category);
}
